export const codeList = {
	User: [
		{
			id: 1,
			label: 'teramed',
			value: 'teramed',
			codeName: 'User',
			parentCodeValue: null,
			orderingIndex: 1,
		},
		{
			id: 2,
			label: 'user',
			value: 'user',
			codeName: 'User',
			parentCodeValue: null,
			orderingIndex: 2,
		},
	],
	ReportTemplate: [
		{
			id: 1,
			label: 'Blank',
			value: 'Blank',
			codeName: 'ReportTemplate',
			parentCodeValue: null,
			orderingIndex: 0,
		},
		{
			id: 2,
			label: 'Colonoscopy',
			value: 'Colonoscopy',
			codeName: 'ReportTemplate',
			parentCodeValue: null,
			orderingIndex: 0,
		},
		{
			id: 3,
			label: 'Colonoscopy_MK',
			value: 'Colonoscopy_MK',
			codeName: 'ReportTemplate',
			parentCodeValue: null,
			orderingIndex: 0,
		},
		{
			id: 4,
			label: 'Colonoscopy_TM',
			value: 'Colonoscopy_TM',
			codeName: 'ReportTemplate',
			parentCodeValue: null,
			orderingIndex: 0,
		},
		{
			id: 5,
			label: 'Gastroscopy',
			value: 'Gastroscopy',
			codeName: 'ReportTemplate',
			parentCodeValue: null,
			orderingIndex: 0,
		},
		{
			id: 6,
			label: 'Gastroscopy_MK',
			value: 'Gastroscopy_MK',
			codeName: 'ReportTemplate',
			parentCodeValue: null,
			orderingIndex: 0,
		},
		{
			id: 7,
			label: 'Gastroscopy_TM',
			value: 'Gastroscopy_TM',
			codeName: 'ReportTemplate',
			parentCodeValue: null,
			orderingIndex: 0,
		},
		{
			id: 8,
			label: 'Sigmoidoscopy',
			value: 'Sigmoidoscopy',
			codeName: 'ReportTemplate',
			parentCodeValue: null,
			orderingIndex: 0,
		},
		{
			id: 9,
			label: 'Sigmoidoscopy_MK',
			value: 'Sigmoidoscopy_MK',
			codeName: 'ReportTemplate',
			parentCodeValue: null,
			orderingIndex: 0,
		},
		{
			id: 10,
			label: 'Sigmoidoscopy_TM',
			value: 'Sigmoidoscopy_TM',
			codeName: 'ReportTemplate',
			parentCodeValue: null,
			orderingIndex: 0,
		},
	],
	AdequateInadequate: [
		{
			id: 62,
			label: 'Adequate',
			value: 'Adequate',
			codeName: 'AdequateInadequate',
			parentCodeValue: '',
			orderingIndex: 1,
		},
		{
			id: 66,
			label: 'Inadequate',
			value: 'Inadequate',
			codeName: 'AdequateInadequate',
			parentCodeValue: '',
			orderingIndex: 2,
		},
	],
	Anaesthetist: [
		{
			id: 162,
			label: 'Dr. Ip Ka Ho',
			value: 'Dr. Ip Ka Ho',
			codeName: 'Anaesthetist',
			parentCodeValue: null,
			orderingIndex: 1,
		},
		{
			id: 163,
			label: 'Dr. Shek Ka Chung',
			value: 'Dr. Shek Ka Chung',
			codeName: 'Anaesthetist',
			parentCodeValue: null,
			orderingIndex: 2,
		},
		{
			id: 164,
			label: 'Dr. Yuen Henry Jeffrey',
			value: 'Dr. Yuen Henry Jeffrey',
			codeName: 'Anaesthetist',
			parentCodeValue: null,
			orderingIndex: 3,
		},
		{
			id: 165,
			label: 'Dr. Yip Chi Pang',
			value: 'Dr. Yip Chi Pang',
			codeName: 'Anaesthetist',
			parentCodeValue: null,
			orderingIndex: 4,
		},
		{
			id: 166,
			label: 'Dr. Lee Chun Wai',
			value: 'Dr. Lee Chun Wai',
			codeName: 'Anaesthetist',
			parentCodeValue: null,
			orderingIndex: 5,
		},
		{
			id: 167,
			label: 'Dr. LeungWang Ho',
			value: 'Dr. LeungWang Ho',
			codeName: 'Anaesthetist',
			parentCodeValue: null,
			orderingIndex: 6,
		},
	],
	'Bowel-Quality-V2': [
		{
			id: 590,
			label: 'Excellent',
			value: 'Excellent',
			codeName: 'Bowel-Quality-V2',
			parentCodeValue: '',
			orderingIndex: 1,
		},
		{
			id: 592,
			label: 'Good',
			value: 'Good',
			codeName: 'Bowel-Quality-V2',
			parentCodeValue: '',
			orderingIndex: 2,
		},
		{
			id: 591,
			label: 'Fair',
			value: 'Fair',
			codeName: 'Bowel-Quality-V2',
			parentCodeValue: '',
			orderingIndex: 3,
		},
	],
	'CLO-Test-Result': [
		{
			id: 594,
			label: 'Pending',
			value: 'Pending',
			codeName: 'CLO-Test-Result',
			parentCodeValue: '',
			orderingIndex: 1,
		},
		{
			id: 593,
			label: 'Positive',
			value: 'Positive',
			codeName: 'CLO-Test-Result',
			parentCodeValue: '',
			orderingIndex: 2,
		},
		{
			id: 595,
			label: 'Negative',
			value: 'Negative',
			codeName: 'CLO-Test-Result',
			parentCodeValue: '',
			orderingIndex: 3,
		},
	],
	Diagnosis: [
		{
			id: 502,
			label: 'Polyp (s) 瘜肉',
			value: 'Polyp (s) 瘜肉',
			codeName: 'Diagnosis',
			parentCodeValue: 'Colonoscopy',
			orderingIndex: 1,
		},
		{
			id: 302,
			label: 'Gastritis (胃炎)',
			value: 'Gastritis (胃炎)',
			codeName: 'Diagnosis',
			parentCodeValue: 'Gastroscopy',
			orderingIndex: 1,
		},
		{
			id: 303,
			label: 'Duodenitis (十二指腸炎)',
			value: 'Duodenitis (十二指腸炎)',
			codeName: 'Diagnosis',
			parentCodeValue: 'Gastroscopy',
			orderingIndex: 2,
		},
		{
			id: 503,
			label: 'Colonic polyp',
			value: 'Colonic polyp',
			codeName: 'Diagnosis',
			parentCodeValue: 'Colonoscopy',
			orderingIndex: 2,
		},
		{
			id: 504,
			label: 'Rectal polyp',
			value: 'Rectal polyp',
			codeName: 'Diagnosis',
			parentCodeValue: 'Colonoscopy',
			orderingIndex: 3,
		},
		{
			id: 304,
			label: 'Oesophagitis (食道炎)',
			value: 'Oesophagitis (食道炎)',
			codeName: 'Diagnosis',
			parentCodeValue: 'Gastroscopy',
			orderingIndex: 3,
		},
		{
			id: 305,
			label: 'Gastric polyp(s) (胃瘜肉)',
			value: 'Gastric polyp(s) (胃瘜肉)',
			codeName: 'Diagnosis',
			parentCodeValue: 'Gastroscopy',
			orderingIndex: 4,
		},
		{
			id: 505,
			label: 'Hemorrhoids 痔瘡',
			value: 'Hemorrhoids 痔瘡',
			codeName: 'Diagnosis',
			parentCodeValue: 'Colonoscopy',
			orderingIndex: 4,
		},
		{
			id: 506,
			label: 'Internal piles (內痔)',
			value: 'Internal piles (內痔)',
			codeName: 'Diagnosis',
			parentCodeValue: 'Colonoscopy',
			orderingIndex: 5,
		},
		{
			id: 306,
			label: 'Duodenal polyp ( 十二指腸瘜肉 )',
			value: 'Duodenal polyp ( 十二指腸瘜肉 )',
			codeName: 'Diagnosis',
			parentCodeValue: 'Gastroscopy',
			orderingIndex: 5,
		},
		{
			id: 307,
			label: 'Oesophageal polyp (食道瘜肉)',
			value: 'Oesophageal polyp (食道瘜肉)',
			codeName: 'Diagnosis',
			parentCodeValue: 'Gastroscopy',
			orderingIndex: 6,
		},
		{
			id: 507,
			label: 'External piles (外痔)',
			value: 'External piles (外痔)',
			codeName: 'Diagnosis',
			parentCodeValue: 'Colonoscopy',
			orderingIndex: 6,
		},
		{
			id: 508,
			label: 'Colitis (結腸炎)',
			value: 'Colitis (結腸炎)',
			codeName: 'Diagnosis',
			parentCodeValue: 'Colonoscopy',
			orderingIndex: 7,
		},
		{
			id: 308,
			label: 'Gastric erosion (胃部糜爛)',
			value: 'Gastric erosion (胃部糜爛)',
			codeName: 'Diagnosis',
			parentCodeValue: 'Gastroscopy',
			orderingIndex: 7,
		},
		{
			id: 309,
			label: 'Gastric ulcer (胃潰瘍)',
			value: 'Gastric ulcer (胃潰瘍)',
			codeName: 'Diagnosis',
			parentCodeValue: 'Gastroscopy',
			orderingIndex: 8,
		},
		{
			id: 509,
			label: 'Diverticulosis of colon (憩室)',
			value: 'Diverticulosis of colon (憩室)',
			codeName: 'Diagnosis',
			parentCodeValue: 'Colonoscopy',
			orderingIndex: 8,
		},
		{
			id: 510,
			label: 'Duverucyka (憩室)',
			value: 'Duverucyka (憩室)',
			codeName: 'Diagnosis',
			parentCodeValue: 'Colonoscopy',
			orderingIndex: 9,
		},
		{
			id: 310,
			label: 'Gastric tumour (胃腄瘤)',
			value: 'Gastric tumour (胃腄瘤)',
			codeName: 'Diagnosis',
			parentCodeValue: 'Gastroscopy',
			orderingIndex: 9,
		},
		{
			id: 311,
			label: 'Fundic gland polyp (s) (胃底腺瘜肉)',
			value: 'Fundic gland polyp (s) (胃底腺瘜肉)',
			codeName: 'Diagnosis',
			parentCodeValue: 'Gastroscopy',
			orderingIndex: 10,
		},
		{
			id: 511,
			label: 'Diverticulitis (憩室炎)',
			value: 'Diverticulitis (憩室炎)',
			codeName: 'Diagnosis',
			parentCodeValue: 'Colonoscopy',
			orderingIndex: 10,
		},
		{
			id: 512,
			label: 'Fistula-in-ano (瘻管 肛瘺)',
			value: 'Fistula-in-ano (瘻管 肛瘺)',
			codeName: 'Diagnosis',
			parentCodeValue: 'Colonoscopy',
			orderingIndex: 11,
		},
		{
			id: 312,
			label: 'Atrophic gastritis (萎縮性胃炎)',
			value: 'Atrophic gastritis (萎縮性胃炎)',
			codeName: 'Diagnosis',
			parentCodeValue: 'Gastroscopy',
			orderingIndex: 11,
		},
		{
			id: 313,
			label: 'Gastric submucosal mass (胃黏膜下層腄物',
			value: 'Gastric submucosal mass (胃黏膜下層腄物',
			codeName: 'Diagnosis',
			parentCodeValue: 'Gastroscopy',
			orderingIndex: 12,
		},
		{
			id: 513,
			label: 'Normal (正常)',
			value: 'Normal (正常)',
			codeName: 'Diagnosis',
			parentCodeValue: 'Colonoscopy',
			orderingIndex: 12,
		},
		{
			id: 514,
			label: 'Pruritis ani',
			value: 'Pruritis ani',
			codeName: 'Diagnosis',
			parentCodeValue: 'Colonoscopy',
			orderingIndex: 13,
		},
		{
			id: 314,
			label: 'Gastric varices (胃部靜脈曲張)',
			value: 'Gastric varices (胃部靜脈曲張)',
			codeName: 'Diagnosis',
			parentCodeValue: 'Gastroscopy',
			orderingIndex: 13,
		},
		{
			id: 315,
			label: 'Healed ulcer (已痊癒的潰瘍)',
			value: 'Healed ulcer (已痊癒的潰瘍)',
			codeName: 'Diagnosis',
			parentCodeValue: 'Gastroscopy',
			orderingIndex: 14,
		},
		{
			id: 515,
			label: 'Ulcerative colitis (潰瘍性結腸炎)',
			value: 'Ulcerative colitis (潰瘍性結腸炎)',
			codeName: 'Diagnosis',
			parentCodeValue: 'Colonoscopy',
			orderingIndex: 14,
		},
		{
			id: 516,
			label: "Crohn's disease (克隆氏病變)",
			value: "Crohn's disease (克隆氏病變)",
			codeName: 'Diagnosis',
			parentCodeValue: 'Colonoscopy',
			orderingIndex: 15,
		},
		{
			id: 316,
			label: 'Portal hypertensive gastropathy',
			value: 'Portal hypertensive gastropathy',
			codeName: 'Diagnosis',
			parentCodeValue: 'Gastroscopy',
			orderingIndex: 15,
		},
		{
			id: 317,
			label: 'Pyloric stenosis (幽門狹窄)',
			value: 'Pyloric stenosis (幽門狹窄)',
			codeName: 'Diagnosis',
			parentCodeValue: 'Gastroscopy',
			orderingIndex: 16,
		},
		{
			id: 517,
			label: 'Diverticulosis (憩室)',
			value: 'Diverticulosis (憩室)',
			codeName: 'Diagnosis',
			parentCodeValue: 'Colonoscopy',
			orderingIndex: 16,
		},
		{
			id: 518,
			label: 'Diverticulum (憩室)',
			value: 'Diverticulum (憩室)',
			codeName: 'Diagnosis',
			parentCodeValue: 'Colonoscopy',
			orderingIndex: 17,
		},
		{
			id: 318,
			label: 'Duondenal erosion ( 十二指腸糜爛 )',
			value: 'Duondenal erosion ( 十二指腸糜爛 )',
			codeName: 'Diagnosis',
			parentCodeValue: 'Gastroscopy',
			orderingIndex: 17,
		},
		{
			id: 319,
			label: 'Duodenal ulcer ( 十二指腸潰瘍 )',
			value: 'Duodenal ulcer ( 十二指腸潰瘍 )',
			codeName: 'Diagnosis',
			parentCodeValue: 'Gastroscopy',
			orderingIndex: 18,
		},
		{
			id: 519,
			label: 'Melanosis Coli',
			value: 'Melanosis Coli',
			codeName: 'Diagnosis',
			parentCodeValue: 'Colonoscopy',
			orderingIndex: 18,
		},
		{
			id: 520,
			label: 'Polypectomy site bleeding',
			value: 'Polypectomy site bleeding',
			codeName: 'Diagnosis',
			parentCodeValue: 'Colonoscopy',
			orderingIndex: 19,
		},
		{
			id: 320,
			label: 'Hiatus hernia (食道裂孔疝氣)',
			value: 'Hiatus hernia (食道裂孔疝氣)',
			codeName: 'Diagnosis',
			parentCodeValue: 'Gastroscopy',
			orderingIndex: 19,
		},
		{
			id: 321,
			label: 'Mallory-Weiss tear (胃食道接口裂)',
			value: 'Mallory-Weiss tear (胃食道接口裂)',
			codeName: 'Diagnosis',
			parentCodeValue: 'Gastroscopy',
			orderingIndex: 20,
		},
		{
			id: 521,
			label: 'Proctitis',
			value: 'Proctitis',
			codeName: 'Diagnosis',
			parentCodeValue: 'Colonoscopy',
			orderingIndex: 20,
		},
		{
			id: 522,
			label: 'Submucosal lesion',
			value: 'Submucosal lesion',
			codeName: 'Diagnosis',
			parentCodeValue: 'Colonoscopy',
			orderingIndex: 21,
		},
		{
			id: 322,
			label: 'Achalasia (食道弛緩不能)',
			value: 'Achalasia (食道弛緩不能)',
			codeName: 'Diagnosis',
			parentCodeValue: 'Gastroscopy',
			orderingIndex: 21,
		},
		{
			id: 323,
			label: "Suspected Barrett's oesophagus (",
			value: "Suspected Barrett's oesophagus (",
			codeName: 'Diagnosis',
			parentCodeValue: 'Gastroscopy',
			orderingIndex: 22,
		},
		{
			id: 523,
			label: 'Tumour',
			value: 'Tumour',
			codeName: 'Diagnosis',
			parentCodeValue: 'Colonoscopy',
			orderingIndex: 22,
		},
		{
			id: 524,
			label: 'Suspected colonic cancer',
			value: 'Suspected colonic cancer',
			codeName: 'Diagnosis',
			parentCodeValue: 'Colonoscopy',
			orderingIndex: 23,
		},
		{
			id: 324,
			label: 'Benign oesophageal stricture (良性',
			value: 'Benign oesophageal stricture (良性',
			codeName: 'Diagnosis',
			parentCodeValue: 'Gastroscopy',
			orderingIndex: 23,
		},
		{
			id: 325,
			label: 'Erosive oesophagitis (糜爛性食道炎)',
			value: 'Erosive oesophagitis (糜爛性食道炎)',
			codeName: 'Diagnosis',
			parentCodeValue: 'Gastroscopy',
			orderingIndex: 24,
		},
		{
			id: 326,
			label: 'Oesophageal fistula (食道瘺管)',
			value: 'Oesophageal fistula (食道瘺管)',
			codeName: 'Diagnosis',
			parentCodeValue: 'Gastroscopy',
			orderingIndex: 25,
		},
		{
			id: 327,
			label: 'Oesophageal submucosal mass (食道黏',
			value: 'Oesophageal submucosal mass (食道黏',
			codeName: 'Diagnosis',
			parentCodeValue: 'Gastroscopy',
			orderingIndex: 26,
		},
		{
			id: 328,
			label: 'Oesophageal tumour I食道腄瘤)',
			value: 'Oesophageal tumour I食道腄瘤)',
			codeName: 'Diagnosis',
			parentCodeValue: 'Gastroscopy',
			orderingIndex: 27,
		},
		{
			id: 329,
			label: 'Oesophageal varices (食道靜脈曲張)',
			value: 'Oesophageal varices (食道靜脈曲張)',
			codeName: 'Diagnosis',
			parentCodeValue: 'Gastroscopy',
			orderingIndex: 28,
		},
		{
			id: 330,
			label: 'Foreign body (異物)',
			value: 'Foreign body (異物)',
			codeName: 'Diagnosis',
			parentCodeValue: 'Gastroscopy',
			orderingIndex: 29,
		},
		{
			id: 331,
			label: 'Normal',
			value: 'Normal',
			codeName: 'Diagnosis',
			parentCodeValue: 'Gastroscopy',
			orderingIndex: 30,
		},
		{
			id: 332,
			label: 'Diverticulum ( 憩室 )',
			value: 'Diverticulum ( 憩室 )',
			codeName: 'Diagnosis',
			parentCodeValue: 'Gastroscopy',
			orderingIndex: 31,
		},
	],
	Dosage: [
		{
			id: 577,
			label: 'mg',
			value: 'mg',
			codeName: 'Dosage',
			parentCodeValue: '',
			orderingIndex: 1,
		},
		{
			id: 578,
			label: 'mcg',
			value: 'mcg',
			codeName: 'Dosage',
			parentCodeValue: '',
			orderingIndex: 2,
		},
	],
	ImageFindings: [
		{
			id: 232,
			label: 'Gastritis',
			value: 'Gastritis',
			codeName: 'ImageFindings',
			parentCodeValue: 'Gastroscopy',
			orderingIndex: 1,
		},
		{
			id: 200,
			label: 'Polyp',
			value: 'Polyp',
			codeName: 'ImageFindings',
			parentCodeValue: 'Colonoscopy',
			orderingIndex: 1,
		},
		{
			id: 201,
			label: 'Lateral Spreading tumor',
			value: 'Lateral Spreading tumor',
			codeName: 'ImageFindings',
			parentCodeValue: 'Colonoscopy',
			orderingIndex: 2,
		},
		{
			id: 233,
			label: 'Duodenitis',
			value: 'Duodenitis',
			codeName: 'ImageFindings',
			parentCodeValue: 'Gastroscopy',
			orderingIndex: 2,
		},
		{
			id: 234,
			label: 'Esophagitis',
			value: 'Esophagitis',
			codeName: 'ImageFindings',
			parentCodeValue: 'Gastroscopy',
			orderingIndex: 3,
		},
		{
			id: 202,
			label: 'Colitis',
			value: 'Colitis',
			codeName: 'ImageFindings',
			parentCodeValue: 'Colonoscopy',
			orderingIndex: 3,
		},
		{
			id: 203,
			label: 'Diverticulum',
			value: 'Diverticulum',
			codeName: 'ImageFindings',
			parentCodeValue: 'Colonoscopy',
			orderingIndex: 4,
		},
		{
			id: 235,
			label: 'Erosion',
			value: 'Erosion',
			codeName: 'ImageFindings',
			parentCodeValue: 'Gastroscopy',
			orderingIndex: 4,
		},
		{
			id: 236,
			label: 'Ulcer',
			value: 'Ulcer',
			codeName: 'ImageFindings',
			parentCodeValue: 'Gastroscopy',
			orderingIndex: 5,
		},
		{
			id: 204,
			label: 'Haemorrhoid',
			value: 'Haemorrhoid',
			codeName: 'ImageFindings',
			parentCodeValue: 'Colonoscopy',
			orderingIndex: 5,
		},
		{
			id: 205,
			label: 'Anal fissure',
			value: 'Anal fissure',
			codeName: 'ImageFindings',
			parentCodeValue: 'Colonoscopy',
			orderingIndex: 6,
		},
		{
			id: 237,
			label: 'Polyp',
			value: 'Polyp',
			codeName: 'ImageFindings',
			parentCodeValue: 'Gastroscopy',
			orderingIndex: 6,
		},
		{
			id: 238,
			label: 'Hiatus Hernia',
			value: 'Hiatus Hernia',
			codeName: 'ImageFindings',
			parentCodeValue: 'Gastroscopy',
			orderingIndex: 7,
		},
		{
			id: 206,
			label: 'Anal skin tag',
			value: 'Anal skin tag',
			codeName: 'ImageFindings',
			parentCodeValue: 'Colonoscopy',
			orderingIndex: 7,
		},
		{
			id: 207,
			label: 'Angioectasia',
			value: 'Angioectasia',
			codeName: 'ImageFindings',
			parentCodeValue: 'Colonoscopy',
			orderingIndex: 8,
		},
		{
			id: 239,
			label: 'Varices',
			value: 'Varices',
			codeName: 'ImageFindings',
			parentCodeValue: 'Gastroscopy',
			orderingIndex: 8,
		},
		{
			id: 240,
			label: 'Angioectasia',
			value: 'Angioectasia',
			codeName: 'ImageFindings',
			parentCodeValue: 'Gastroscopy',
			orderingIndex: 9,
		},
		{
			id: 208,
			label: 'Scar',
			value: 'Scar',
			codeName: 'ImageFindings',
			parentCodeValue: 'Colonoscopy',
			orderingIndex: 9,
		},
		{
			id: 209,
			label: 'Polypectomy site',
			value: 'Polypectomy site',
			codeName: 'ImageFindings',
			parentCodeValue: 'Colonoscopy',
			orderingIndex: 10,
		},
		{
			id: 241,
			label: 'Atrophic Gastritis',
			value: 'Atrophic Gastritis',
			codeName: 'ImageFindings',
			parentCodeValue: 'Gastroscopy',
			orderingIndex: 10,
		},
		{
			id: 242,
			label: "Barrett's Esophagus",
			value: "Barrett's Esophagus",
			codeName: 'ImageFindings',
			parentCodeValue: 'Gastroscopy',
			orderingIndex: 11,
		},
		{
			id: 210,
			label: 'Condylomas',
			value: 'Condylomas',
			codeName: 'ImageFindings',
			parentCodeValue: 'Colonoscopy',
			orderingIndex: 11,
		},
		{
			id: 211,
			label: 'Erosion',
			value: 'Erosion',
			codeName: 'ImageFindings',
			parentCodeValue: 'Colonoscopy',
			orderingIndex: 12,
		},
		{
			id: 243,
			label: 'Candidiasis',
			value: 'Candidiasis',
			codeName: 'ImageFindings',
			parentCodeValue: 'Gastroscopy',
			orderingIndex: 12,
		},
		{
			id: 244,
			label: 'Deformity',
			value: 'Deformity',
			codeName: 'ImageFindings',
			parentCodeValue: 'Gastroscopy',
			orderingIndex: 13,
		},
		{
			id: 212,
			label: 'Erythematous (Hypermic)',
			value: 'Erythematous (Hypermic)',
			codeName: 'ImageFindings',
			parentCodeValue: 'Colonoscopy',
			orderingIndex: 13,
		},
		{
			id: 213,
			label: 'Evidence of previous surgery',
			value: 'Evidence of previous surgery',
			codeName: 'ImageFindings',
			parentCodeValue: 'Colonoscopy',
			orderingIndex: 14,
		},
		{
			id: 245,
			label: 'Pyloric stenosis',
			value: 'Pyloric stenosis',
			codeName: 'ImageFindings',
			parentCodeValue: 'Gastroscopy',
			orderingIndex: 14,
		},
		{
			id: 246,
			label: 'Dieulafoy lesion',
			value: 'Dieulafoy lesion',
			codeName: 'ImageFindings',
			parentCodeValue: 'Gastroscopy',
			orderingIndex: 15,
		},
		{
			id: 214,
			label: 'Excavated lesion',
			value: 'Excavated lesion',
			codeName: 'ImageFindings',
			parentCodeValue: 'Colonoscopy',
			orderingIndex: 15,
		},
		{
			id: 215,
			label: 'Exudate',
			value: 'Exudate',
			codeName: 'ImageFindings',
			parentCodeValue: 'Colonoscopy',
			orderingIndex: 16,
		},
		{
			id: 247,
			label: 'Diverticulum',
			value: 'Diverticulum',
			codeName: 'ImageFindings',
			parentCodeValue: 'Gastroscopy',
			orderingIndex: 16,
		},
		{
			id: 248,
			label: 'Evidence of previous surgery',
			value: 'Evidence of previous surgery',
			codeName: 'ImageFindings',
			parentCodeValue: 'Gastroscopy',
			orderingIndex: 17,
		},
		{
			id: 216,
			label: 'Fistula',
			value: 'Fistula',
			codeName: 'ImageFindings',
			parentCodeValue: 'Colonoscopy',
			orderingIndex: 17,
		},
		{
			id: 217,
			label: 'Foreign body',
			value: 'Foreign body',
			codeName: 'ImageFindings',
			parentCodeValue: 'Colonoscopy',
			orderingIndex: 18,
		},
		{
			id: 249,
			label: 'Extrinsic compression',
			value: 'Extrinsic compression',
			codeName: 'ImageFindings',
			parentCodeValue: 'Gastroscopy',
			orderingIndex: 18,
		},
		{
			id: 250,
			label: 'Flat lesions',
			value: 'Flat lesions',
			codeName: 'ImageFindings',
			parentCodeValue: 'Gastroscopy',
			orderingIndex: 19,
		},
		{
			id: 218,
			label: 'Colonic lipoma',
			value: 'Colonic lipoma',
			codeName: 'ImageFindings',
			parentCodeValue: 'Colonoscopy',
			orderingIndex: 19,
		},
		{
			id: 219,
			label: 'Melanosis coli',
			value: 'Melanosis coli',
			codeName: 'ImageFindings',
			parentCodeValue: 'Colonoscopy',
			orderingIndex: 20,
		},
		{
			id: 251,
			label: 'Foreign Body',
			value: 'Foreign Body',
			codeName: 'ImageFindings',
			parentCodeValue: 'Gastroscopy',
			orderingIndex: 20,
		},
		{
			id: 252,
			label: 'Lipoma',
			value: 'Lipoma',
			codeName: 'ImageFindings',
			parentCodeValue: 'Gastroscopy',
			orderingIndex: 21,
		},
		{
			id: 220,
			label: 'NBI image',
			value: 'NBI image',
			codeName: 'ImageFindings',
			parentCodeValue: 'Colonoscopy',
			orderingIndex: 21,
		},
		{
			id: 221,
			label: 'Polypectomy site, post cauterisa',
			value: 'Polypectomy site, post cauterisa',
			codeName: 'ImageFindings',
			parentCodeValue: 'Colonoscopy',
			orderingIndex: 22,
		},
		{
			id: 253,
			label: 'Mallory-Weiss tear',
			value: 'Mallory-Weiss tear',
			codeName: 'ImageFindings',
			parentCodeValue: 'Gastroscopy',
			orderingIndex: 22,
		},
		{
			id: 254,
			label: 'NBI image',
			value: 'NBI image',
			codeName: 'ImageFindings',
			parentCodeValue: 'Gastroscopy',
			orderingIndex: 23,
		},
		{
			id: 222,
			label: 'Pseudomembrance',
			value: 'Pseudomembrance',
			codeName: 'ImageFindings',
			parentCodeValue: 'Colonoscopy',
			orderingIndex: 23,
		},
		{
			id: 223,
			label: 'Pseudopolyp',
			value: 'Pseudopolyp',
			codeName: 'ImageFindings',
			parentCodeValue: 'Colonoscopy',
			orderingIndex: 24,
		},
		{
			id: 255,
			label: 'Scar',
			value: 'Scar',
			codeName: 'ImageFindings',
			parentCodeValue: 'Gastroscopy',
			orderingIndex: 24,
		},
		{
			id: 256,
			label: 'Stricture',
			value: 'Stricture',
			codeName: 'ImageFindings',
			parentCodeValue: 'Gastroscopy',
			orderingIndex: 25,
		},
		{
			id: 224,
			label: 'Pseudopolyps',
			value: 'Pseudopolyps',
			codeName: 'ImageFindings',
			parentCodeValue: 'Colonoscopy',
			orderingIndex: 25,
		},
		{
			id: 225,
			label: 'Stenosis',
			value: 'Stenosis',
			codeName: 'ImageFindings',
			parentCodeValue: 'Colonoscopy',
			orderingIndex: 26,
		},
		{
			id: 257,
			label: 'Submucosal mass',
			value: 'Submucosal mass',
			codeName: 'ImageFindings',
			parentCodeValue: 'Gastroscopy',
			orderingIndex: 26,
		},
		{
			id: 258,
			label: 'Tongue like extensions',
			value: 'Tongue like extensions',
			codeName: 'ImageFindings',
			parentCodeValue: 'Gastroscopy',
			orderingIndex: 27,
		},
		{
			id: 226,
			label: 'Stent',
			value: 'Stent',
			codeName: 'ImageFindings',
			parentCodeValue: 'Colonoscopy',
			orderingIndex: 27,
		},
		{
			id: 227,
			label: 'Submucosal mass',
			value: 'Submucosal mass',
			codeName: 'ImageFindings',
			parentCodeValue: 'Colonoscopy',
			orderingIndex: 28,
		},
		{
			id: 259,
			label: 'Tumour',
			value: 'Tumour',
			codeName: 'ImageFindings',
			parentCodeValue: 'Gastroscopy',
			orderingIndex: 28,
		},
		{
			id: 228,
			label: 'Suture granuloma',
			value: 'Suture granuloma',
			codeName: 'ImageFindings',
			parentCodeValue: 'Colonoscopy',
			orderingIndex: 29,
		},
		{
			id: 229,
			label: 'Tumour',
			value: 'Tumour',
			codeName: 'ImageFindings',
			parentCodeValue: 'Colonoscopy',
			orderingIndex: 30,
		},
		{
			id: 230,
			label: 'Ulcer',
			value: 'Ulcer',
			codeName: 'ImageFindings',
			parentCodeValue: 'Colonoscopy',
			orderingIndex: 31,
		},
		{
			id: 231,
			label: 'Ulerative mucosa',
			value: 'Ulerative mucosa',
			codeName: 'ImageFindings',
			parentCodeValue: 'Colonoscopy',
			orderingIndex: 32,
		},
	],
	ImageSites: [
		{
			id: 260,
			label: 'Anal canal',
			value: 'Anal canal',
			codeName: 'ImageSites',
			parentCodeValue: 'Gastroscopy',
			orderingIndex: 1,
		},
		{
			id: 281,
			label: 'Anal canal',
			value: 'Anal canal',
			codeName: 'ImageSites',
			parentCodeValue: 'Colonoscopy',
			orderingIndex: 1,
		},
		{
			id: 282,
			label: 'Anastomosis',
			value: 'Anastomosis',
			codeName: 'ImageSites',
			parentCodeValue: 'Colonoscopy',
			orderingIndex: 2,
		},
		{
			id: 261,
			label: 'Anastomosis',
			value: 'Anastomosis',
			codeName: 'ImageSites',
			parentCodeValue: 'Gastroscopy',
			orderingIndex: 2,
		},
		{
			id: 262,
			label: 'Anus',
			value: 'Anus',
			codeName: 'ImageSites',
			parentCodeValue: 'Gastroscopy',
			orderingIndex: 3,
		},
		{
			id: 283,
			label: 'Anus',
			value: 'Anus',
			codeName: 'ImageSites',
			parentCodeValue: 'Colonoscopy',
			orderingIndex: 3,
		},
		{
			id: 284,
			label: 'Appendiceal opening',
			value: 'Appendiceal opening',
			codeName: 'ImageSites',
			parentCodeValue: 'Colonoscopy',
			orderingIndex: 4,
		},
		{
			id: 263,
			label: 'Appendiceal opening',
			value: 'Appendiceal opening',
			codeName: 'ImageSites',
			parentCodeValue: 'Gastroscopy',
			orderingIndex: 4,
		},
		{
			id: 264,
			label: 'Appendiceal orifice and caecum',
			value: 'Appendiceal orifice and caecum',
			codeName: 'ImageSites',
			parentCodeValue: 'Gastroscopy',
			orderingIndex: 5,
		},
		{
			id: 285,
			label: 'Appendiceal orifice and caeum',
			value: 'Appendiceal orifice and caeum',
			codeName: 'ImageSites',
			parentCodeValue: 'Colonoscopy',
			orderingIndex: 5,
		},
		{
			id: 286,
			label: 'Ascending colon',
			value: 'Ascending colon',
			codeName: 'ImageSites',
			parentCodeValue: 'Colonoscopy',
			orderingIndex: 6,
		},
		{
			id: 265,
			label: 'Ascending colon',
			value: 'Ascending colon',
			codeName: 'ImageSites',
			parentCodeValue: 'Gastroscopy',
			orderingIndex: 6,
		},
		{
			id: 266,
			label: 'Caecum',
			value: 'Caecum',
			codeName: 'ImageSites',
			parentCodeValue: 'Gastroscopy',
			orderingIndex: 7,
		},
		{
			id: 287,
			label: 'Caecum',
			value: 'Caecum',
			codeName: 'ImageSites',
			parentCodeValue: 'Colonoscopy',
			orderingIndex: 7,
		},
		{
			id: 288,
			label: 'Descending colon',
			value: 'Descending colon',
			codeName: 'ImageSites',
			parentCodeValue: 'Colonoscopy',
			orderingIndex: 8,
		},
		{
			id: 267,
			label: 'Descending colon',
			value: 'Descending colon',
			codeName: 'ImageSites',
			parentCodeValue: 'Gastroscopy',
			orderingIndex: 8,
		},
		{
			id: 268,
			label: 'Hepatic flexure',
			value: 'Hepatic flexure',
			codeName: 'ImageSites',
			parentCodeValue: 'Gastroscopy',
			orderingIndex: 9,
		},
		{
			id: 289,
			label: 'Hepatic flexure',
			value: 'Hepatic flexure',
			codeName: 'ImageSites',
			parentCodeValue: 'Colonoscopy',
			orderingIndex: 9,
		},
		{
			id: 290,
			label: 'lleo-caecal valve',
			value: 'lleo-caecal valve',
			codeName: 'ImageSites',
			parentCodeValue: 'Colonoscopy',
			orderingIndex: 10,
		},
		{
			id: 269,
			label: 'Ileo-caecal valve',
			value: 'Ileo-caecal valve',
			codeName: 'ImageSites',
			parentCodeValue: 'Gastroscopy',
			orderingIndex: 10,
		},
		{
			id: 270,
			label: 'Ileum',
			value: 'Ileum',
			codeName: 'ImageSites',
			parentCodeValue: 'Gastroscopy',
			orderingIndex: 11,
		},
		{
			id: 291,
			label: 'Ileum',
			value: 'Ileum',
			codeName: 'ImageSites',
			parentCodeValue: 'Colonoscopy',
			orderingIndex: 11,
		},
		{
			id: 292,
			label: 'Lower rectum',
			value: 'Lower rectum',
			codeName: 'ImageSites',
			parentCodeValue: 'Colonoscopy',
			orderingIndex: 12,
		},
		{
			id: 271,
			label: 'Lower rectum',
			value: 'Lower rectum',
			codeName: 'ImageSites',
			parentCodeValue: 'Gastroscopy',
			orderingIndex: 12,
		},
		{
			id: 272,
			label: 'Rectosigmoid',
			value: 'Rectosigmoid',
			codeName: 'ImageSites',
			parentCodeValue: 'Gastroscopy',
			orderingIndex: 13,
		},
		{
			id: 293,
			label: 'Rectosigmoid',
			value: 'Rectosigmoid',
			codeName: 'ImageSites',
			parentCodeValue: 'Colonoscopy',
			orderingIndex: 13,
		},
		{
			id: 294,
			label: 'Rectum',
			value: 'Rectum',
			codeName: 'ImageSites',
			parentCodeValue: 'Colonoscopy',
			orderingIndex: 14,
		},
		{
			id: 273,
			label: 'Rectum',
			value: 'Rectum',
			codeName: 'ImageSites',
			parentCodeValue: 'Gastroscopy',
			orderingIndex: 14,
		},
		{
			id: 274,
			label: 'Retroflexion and inside view of',
			value: 'Retroflexion and inside view of',
			codeName: 'ImageSites',
			parentCodeValue: 'Gastroscopy',
			orderingIndex: 15,
		},
		{
			id: 295,
			label: 'Retroflexion and inside view of',
			value: 'Retroflexion and inside view of',
			codeName: 'ImageSites',
			parentCodeValue: 'Colonoscopy',
			orderingIndex: 15,
		},
		{
			id: 296,
			label: 'Sigmoid colon',
			value: 'Sigmoid colon',
			codeName: 'ImageSites',
			parentCodeValue: 'Colonoscopy',
			orderingIndex: 16,
		},
		{
			id: 275,
			label: 'Sigmoid colon',
			value: 'Sigmoid colon',
			codeName: 'ImageSites',
			parentCodeValue: 'Gastroscopy',
			orderingIndex: 16,
		},
		{
			id: 276,
			label: 'Splenic flexure',
			value: 'Splenic flexure',
			codeName: 'ImageSites',
			parentCodeValue: 'Gastroscopy',
			orderingIndex: 17,
		},
		{
			id: 297,
			label: 'Splenic flexure',
			value: 'Splenic flexure',
			codeName: 'ImageSites',
			parentCodeValue: 'Colonoscopy',
			orderingIndex: 17,
		},
		{
			id: 298,
			label: 'Stoma',
			value: 'Stoma',
			codeName: 'ImageSites',
			parentCodeValue: 'Colonoscopy',
			orderingIndex: 18,
		},
		{
			id: 277,
			label: 'Stoma',
			value: 'Stoma',
			codeName: 'ImageSites',
			parentCodeValue: 'Gastroscopy',
			orderingIndex: 18,
		},
		{
			id: 278,
			label: 'Terminal ileum',
			value: 'Terminal ileum',
			codeName: 'ImageSites',
			parentCodeValue: 'Gastroscopy',
			orderingIndex: 19,
		},
		{
			id: 299,
			label: 'Terminal ileum',
			value: 'Terminal ileum',
			codeName: 'ImageSites',
			parentCodeValue: 'Colonoscopy',
			orderingIndex: 19,
		},
		{
			id: 300,
			label: 'Transverse colon',
			value: 'Transverse colon',
			codeName: 'ImageSites',
			parentCodeValue: 'Colonoscopy',
			orderingIndex: 20,
		},
		{
			id: 279,
			label: 'Transverse colon',
			value: 'Transverse colon',
			codeName: 'ImageSites',
			parentCodeValue: 'Gastroscopy',
			orderingIndex: 20,
		},
		{
			id: 280,
			label: 'Ileo-colic anastomsis',
			value: 'Ileo-colic anastomsis',
			codeName: 'ImageSites',
			parentCodeValue: 'Gastroscopy',
			orderingIndex: 21,
		},
		{
			id: 301,
			label: 'Ileo-colic anastomsis',
			value: 'Ileo-colic anastomsis',
			codeName: 'ImageSites',
			parentCodeValue: 'Colonoscopy',
			orderingIndex: 21,
		},
	],
	Indication: [
		{
			id: 14,
			label: 'Abdominal distress / pain',
			value: 'Abdominal distress / pain',
			codeName: 'Indication',
			parentCodeValue: 'Colonoscopy',
			orderingIndex: 1,
		},
		{
			id: 30,
			label: 'Abdominal distress / pain',
			value: 'Abdominal distress / pain',
			codeName: 'Indication',
			parentCodeValue: 'Gastroscopy',
			orderingIndex: 1,
		},
		{
			id: 31,
			label: 'Anemia',
			value: 'Anemia',
			codeName: 'Indication',
			parentCodeValue: 'Gastroscopy',
			orderingIndex: 2,
		},
		{
			id: 15,
			label: 'Per rectal bleeding',
			value: 'Per rectal bleeding',
			codeName: 'Indication',
			parentCodeValue: 'Colonoscopy',
			orderingIndex: 2,
		},
		{
			id: 16,
			label: 'Altered bowel habbit',
			value: 'Altered bowel habbit',
			codeName: 'Indication',
			parentCodeValue: 'Colonoscopy',
			orderingIndex: 3,
		},
		{
			id: 32,
			label: 'Cancer surveillance',
			value: 'Cancer surveillance',
			codeName: 'Indication',
			parentCodeValue: 'Gastroscopy',
			orderingIndex: 3,
		},
		{
			id: 33,
			label: 'Chest pain',
			value: 'Chest pain',
			codeName: 'Indication',
			parentCodeValue: 'Gastroscopy',
			orderingIndex: 4,
		},
		{
			id: 17,
			label: 'Diarrhoea',
			value: 'Diarrhoea',
			codeName: 'Indication',
			parentCodeValue: 'Colonoscopy',
			orderingIndex: 4,
		},
		{
			id: 18,
			label: 'Constipation',
			value: 'Constipation',
			codeName: 'Indication',
			parentCodeValue: 'Colonoscopy',
			orderingIndex: 5,
		},
		{
			id: 34,
			label: 'Coffee ground vomiting',
			value: 'Coffee ground vomiting',
			codeName: 'Indication',
			parentCodeValue: 'Gastroscopy',
			orderingIndex: 5,
		},
		{
			id: 35,
			label: 'Dysphagia',
			value: 'Dysphagia',
			codeName: 'Indication',
			parentCodeValue: 'Gastroscopy',
			orderingIndex: 6,
		},
		{
			id: 19,
			label: 'Anemia',
			value: 'Anemia',
			codeName: 'Indication',
			parentCodeValue: 'Colonoscopy',
			orderingIndex: 6,
		},
		{
			id: 20,
			label: 'Abnormal imaging',
			value: 'Abnormal imaging',
			codeName: 'Indication',
			parentCodeValue: 'Colonoscopy',
			orderingIndex: 7,
		},
		{
			id: 36,
			label: 'Epigastric pain',
			value: 'Epigastric pain',
			codeName: 'Indication',
			parentCodeValue: 'Gastroscopy',
			orderingIndex: 7,
		},
		{
			id: 37,
			label: 'Haematemesis',
			value: 'Haematemesis',
			codeName: 'Indication',
			parentCodeValue: 'Gastroscopy',
			orderingIndex: 8,
		},
		{
			id: 21,
			label: 'Raised tumor marker',
			value: 'Raised tumor marker',
			codeName: 'Indication',
			parentCodeValue: 'Colonoscopy',
			orderingIndex: 8,
		},
		{
			id: 22,
			label: 'Cancer surveillance',
			value: 'Cancer surveillance',
			codeName: 'Indication',
			parentCodeValue: 'Colonoscopy',
			orderingIndex: 9,
		},
		{
			id: 38,
			label: 'Melena',
			value: 'Melena',
			codeName: 'Indication',
			parentCodeValue: 'Gastroscopy',
			orderingIndex: 9,
		},
		{
			id: 23,
			label: 'Melena',
			value: 'Melena',
			codeName: 'Indication',
			parentCodeValue: 'Colonoscopy',
			orderingIndex: 10,
		},
		{
			id: 51,
			label: 'Ulcer follow up',
			value: 'Ulcer follow up',
			codeName: 'Indication',
			parentCodeValue: 'Gastroscopy',
			orderingIndex: 10,
		},
		{
			id: 24,
			label: 'Nausea / Vomiting',
			value: 'Nausea / Vomiting',
			codeName: 'Indication',
			parentCodeValue: 'Colonoscopy',
			orderingIndex: 11,
		},
		{
			id: 40,
			label: 'Nausea / Vomiting',
			value: 'Nausea / Vomiting',
			codeName: 'Indication',
			parentCodeValue: 'Gastroscopy',
			orderingIndex: 11,
		},
		{
			id: 41,
			label: 'Positive fecal occult blood test',
			value: 'Positive fecal occult blood test',
			codeName: 'Indication',
			parentCodeValue: 'Gastroscopy',
			orderingIndex: 12,
		},
		{
			id: 25,
			label: 'Positive fecal occult blood test',
			value: 'Positive fecal occult blood test',
			codeName: 'Indication',
			parentCodeValue: 'Colonoscopy',
			orderingIndex: 12,
		},
		{
			id: 26,
			label: 'Weight loss',
			value: 'Weight loss',
			codeName: 'Indication',
			parentCodeValue: 'Colonoscopy',
			orderingIndex: 13,
		},
		{
			id: 42,
			label: 'Reflux / heartburn',
			value: 'Reflux / heartburn',
			codeName: 'Indication',
			parentCodeValue: 'Gastroscopy',
			orderingIndex: 13,
		},
		{
			id: 43,
			label: 'Weight loss',
			value: 'Weight loss',
			codeName: 'Indication',
			parentCodeValue: 'Gastroscopy',
			orderingIndex: 14,
		},
		{
			id: 27,
			label: 'Inflammatory bowel disease follo',
			value: 'Inflammatory bowel disease follo',
			codeName: 'Indication',
			parentCodeValue: 'Colonoscopy',
			orderingIndex: 14,
		},
		{
			id: 28,
			label: 'Proctalgia',
			value: 'Proctalgia',
			codeName: 'Indication',
			parentCodeValue: 'Colonoscopy',
			orderingIndex: 15,
		},
		{
			id: 44,
			label: 'Heartburn',
			value: 'Heartburn',
			codeName: 'Indication',
			parentCodeValue: 'Gastroscopy',
			orderingIndex: 15,
		},
		{
			id: 45,
			label: 'Raised tumor marker',
			value: 'Raised tumor marker',
			codeName: 'Indication',
			parentCodeValue: 'Gastroscopy',
			orderingIndex: 16,
		},
		{
			id: 29,
			label: 'Suspected inflammatory bowel dis',
			value: 'Suspected inflammatory bowel dis',
			codeName: 'Indication',
			parentCodeValue: 'Colonoscopy',
			orderingIndex: 16,
		},
		{
			id: 46,
			label: 'Globus sensation',
			value: 'Globus sensation',
			codeName: 'Indication',
			parentCodeValue: 'Gastroscopy',
			orderingIndex: 17,
		},
	],
	Instrument: [
		{
			id: 12,
			label: 'EC-760R-V/L-1C729K466',
			value: 'EC-760R-V/L-1C729K466',
			codeName: 'Instrument',
			parentCodeValue: 'Colonoscopy',
			orderingIndex: 1,
		},
		{
			id: 549,
			label: 'EC-580RD/L-1C691K168',
			value: 'EC-580RD/L-1C691K168',
			codeName: 'Instrument',
			parentCodeValue: 'Gastroscopy',
			orderingIndex: 1,
		},
		{
			id: 13,
			label: 'EC-760-V/L-1G402k417',
			value: 'EC-760-V/L-1G402k417',
			codeName: 'Instrument',
			parentCodeValue: 'Colonoscopy',
			orderingIndex: 2,
		},
	],
	'MBI-AI': [
		{
			id: 568,
			label: 'MBI',
			value: 'MBI',
			codeName: 'MBI-AI',
			parentCodeValue: '',
			orderingIndex: 1,
		},
		{
			id: 569,
			label: 'AI',
			value: 'AI',
			codeName: 'MBI-AI',
			parentCodeValue: '',
			orderingIndex: 2,
		},
	],
	PerformingPhysician: [
		{
			id: 729,
			label: 'PerformingPhysician1',
			value: 'PerformingPhysician1',
			codeName: 'PerformingPhysician',
			parentCodeValue: '',
			orderingIndex: 1,
		},
		{
			id: 730,
			label: 'PerformingPhysician2',
			value: 'PerformingPhysician2',
			codeName: 'PerformingPhysician',
			parentCodeValue: '',
			orderingIndex: 2,
		},
	],
	Procedure: [
		{
			id: 441,
			label: 'Colonoscopy (大腸內視鏡)',
			value: 'Colonoscopy (大腸內視鏡)',
			codeName: 'Procedure',
			parentCodeValue: 'Colonoscopy',
			orderingIndex: 1,
		},
		{
			id: 434,
			label: 'OGD (食道、胃、十二指腸內窺鏡)',
			value: 'OGD (食道、胃、十二指腸內窺鏡)',
			codeName: 'Procedure',
			parentCodeValue: 'Gastroscopy',
			orderingIndex: 1,
		},
		{
			id: 435,
			label: 'Biopsy + CLO Test (組織活檢+幽門螺旋菌測試)',
			value: 'Biopsy + CLO Test (組織活檢+幽門螺旋菌測試)',
			codeName: 'Procedure',
			parentCodeValue: 'Gastroscopy',
			orderingIndex: 2,
		},
		{
			id: 442,
			label: 'Polypectomy (瘜肉切除)',
			value: 'Polypectomy (瘜肉切除)',
			codeName: 'Procedure',
			parentCodeValue: 'Colonoscopy',
			orderingIndex: 2,
		},
		{
			id: 443,
			label: 'Banding of haemorrhoids Banding',
			value: 'Banding of haemorrhoids Banding',
			codeName: 'Procedure',
			parentCodeValue: 'Colonoscopy',
			orderingIndex: 3,
		},
		{
			id: 436,
			label: 'Polypectomy (瘜肉切除術)',
			value: 'Polypectomy (瘜肉切除術)',
			codeName: 'Procedure',
			parentCodeValue: 'Gastroscopy',
			orderingIndex: 3,
		},
		{
			id: 437,
			label: 'Biopsy (組織活檢)',
			value: 'Biopsy (組織活檢)',
			codeName: 'Procedure',
			parentCodeValue: 'Gastroscopy',
			orderingIndex: 4,
		},
		{
			id: 444,
			label: 'Biopsy (組織活檢)',
			value: 'Biopsy (組織活檢)',
			codeName: 'Procedure',
			parentCodeValue: 'Colonoscopy',
			orderingIndex: 4,
		},
		{
			id: 445,
			label: 'Haemostasis (止血程序)',
			value: 'Haemostasis (止血程序)',
			codeName: 'Procedure',
			parentCodeValue: 'Colonoscopy',
			orderingIndex: 5,
		},
		{
			id: 438,
			label: 'Haemostasis (止血程序)',
			value: 'Haemostasis (止血程序)',
			codeName: 'Procedure',
			parentCodeValue: 'Gastroscopy',
			orderingIndex: 5,
		},
		{
			id: 439,
			label: 'CLO Test (幽門螺旋菌測試)',
			value: 'CLO Test (幽門螺旋菌測試)',
			codeName: 'Procedure',
			parentCodeValue: 'Gastroscopy',
			orderingIndex: 6,
		},
		{
			id: 446,
			label: 'Sigmoidoscopy (乙狀結腸鏡檢查)',
			value: 'Sigmoidoscopy (乙狀結腸鏡檢查)',
			codeName: 'Procedure',
			parentCodeValue: 'Colonoscopy',
			orderingIndex: 6,
		},
		{
			id: 447,
			label: 'Foreign body removal (異物移除)',
			value: 'Foreign body removal (異物移除)',
			codeName: 'Procedure',
			parentCodeValue: 'Colonoscopy',
			orderingIndex: 7,
		},
		{
			id: 440,
			label: 'Foreign body removal (異物移除)',
			value: 'Foreign body removal (異物移除)',
			codeName: 'Procedure',
			parentCodeValue: 'Gastroscopy',
			orderingIndex: 7,
		},
	],
	ReferringPhysician: [
		{
			id: 723,
			label: 'ReferringPhysician1',
			value: 'ReferringPhysician1',
			codeName: 'ReferringPhysician',
			parentCodeValue: '',
			orderingIndex: 1,
		},
		{
			id: 726,
			label: 'ReferringPhysician2',
			value: 'ReferringPhysician2',
			codeName: 'ReferringPhysician',
			parentCodeValue: '',
			orderingIndex: 2,
		},
	],
	ReportingPhysician: [
		{
			id: 724,
			label: 'ReportingPhysician1',
			value: 'ReportingPhysician1',
			codeName: 'ReportingPhysician',
			parentCodeValue: '',
			orderingIndex: 1,
		},
		{
			id: 727,
			label: 'ReportingPhysician2',
			value: 'ReportingPhysician2',
			codeName: 'ReportingPhysician',
			parentCodeValue: '',
			orderingIndex: 2,
		},
	],
	ReportTitle: [
		{
			id: 70,
			label: 'Colonoscopy',
			value: 'COLONOSCOPY REPORT',
			codeName: 'ReportTitle',
			parentCodeValue: null,
			orderingIndex: 1,
		},
		{
			id: 71,
			label: 'Gastroscopy',
			value: 'GASTROSCOPY REPORT',
			codeName: 'ReportTitle',
			parentCodeValue: null,
			orderingIndex: 2,
		},
	],
	Sedation: [
		{
			id: 54,
			label: 'MAC',
			value: 'MAC',
			codeName: 'Sedation',
			parentCodeValue: null,
			orderingIndex: 1,
		},
		{
			id: 58,
			label: 'Midazolam',
			value: 'Midazolam',
			codeName: 'Sedation',
			parentCodeValue: null,
			orderingIndex: 2,
		},
		{
			id: 60,
			label: 'Fentanyl',
			value: 'Fentanyl',
			codeName: 'Sedation',
			parentCodeValue: null,
			orderingIndex: 3,
		},
	],
	YesNo: [
		{
			id: 67,
			label: 'Yes',
			value: 'Yes',
			codeName: 'YesNo',
			parentCodeValue: null,
			orderingIndex: 1,
		},
		{
			id: 69,
			label: 'No',
			value: 'No',
			codeName: 'YesNo',
			parentCodeValue: null,
			orderingIndex: 2,
		},
	],
};
