import { fakeDefine } from './fake-data.ts';

export const codeList = {
	AdequateInadequate: [
		{
			Id: 62,
			Label: 'Adequate',
			Value: 'Adequate',
			CodeName: 'AdequateInadequate',
			ParentCodeValue: '',
			OrderingIndex: 1,
		},
		{
			Id: 66,
			Label: 'Inadequate',
			Value: 'Inadequate',
			CodeName: 'AdequateInadequate',
			ParentCodeValue: '',
			OrderingIndex: 2,
		},
	],
	Anaesthetist: [
		{
			Id: 162,
			Label: 'Dr. Ip Ka Ho',
			Value: 'Dr. Ip Ka Ho',
			CodeName: 'Anaesthetist',
			ParentCodeValue: '',
			OrderingIndex: 1,
		},
		{
			Id: 163,
			Label: 'Dr. Shek Ka Chung',
			Value: 'Dr. Shek Ka Chung',
			CodeName: 'Anaesthetist',
			ParentCodeValue: '',
			OrderingIndex: 2,
		},
	],
	'Bowel-Quality-V2': [
		{
			Id: 660,
			Label: 'Good',
			Value: 'Good',
			CodeName: 'Bowel-Quality-V2',
			ParentCodeValue: '',
			OrderingIndex: 1,
		},
		{
			Id: 661,
			Label: 'Fair',
			Value: 'Fair',
			CodeName: 'Bowel-Quality-V2',
			ParentCodeValue: '',
			OrderingIndex: 2,
		},
		{
			Id: 659,
			Label: 'Poor',
			Value: 'Poor',
			CodeName: 'Bowel-Quality-V2',
			ParentCodeValue: '',
			OrderingIndex: 3,
		},
	],
	'CLO-Test-Result': [
		{
			Id: 663,
			Label: 'Pending',
			Value: 'Pending',
			CodeName: 'CLO-Test-Result',
			ParentCodeValue: '',
			OrderingIndex: 1,
		},
		{
			Id: 662,
			Label: 'Positive',
			Value: 'Positive',
			CodeName: 'CLO-Test-Result',
			ParentCodeValue: '',
			OrderingIndex: 2,
		},
		{
			Id: 664,
			Label: 'Negative',
			Value: 'Negative',
			CodeName: 'CLO-Test-Result',
			ParentCodeValue: '',
			OrderingIndex: 3,
		},
	],
	Diagnosis: [
		{
			Id: 502,
			Label: 'Polyp (s) (瘜肉)',
			Value: 'Polyp (s) (瘜肉)',
			CodeName: 'Diagnosis',
			ParentCodeValue: 'Colonoscopy',
			OrderingIndex: 1,
		},
		{
			Id: 503,
			Label: 'Colonic polyp (腸瘜肉)',
			Value: 'Colonic polyp (腸瘜肉)',
			CodeName: 'Diagnosis',
			ParentCodeValue: 'Colonoscopy',
			OrderingIndex: 2,
		},
		{
			Id: 504,
			Label: 'Rectal polyp (瘜肉)',
			Value: 'Rectal polyp (瘜肉)',
			CodeName: 'Diagnosis',
			ParentCodeValue: 'Colonoscopy',
			OrderingIndex: 3,
		},
		{
			Id: 505,
			Label: 'Hemorrhoids 痔瘡',
			Value: 'Hemorrhoids 痔瘡',
			CodeName: 'Diagnosis',
			ParentCodeValue: 'Colonoscopy',
			OrderingIndex: 4,
		},
		{
			Id: 506,
			Label: 'Internal piles (內痔)',
			Value: 'Internal piles (內痔)',
			CodeName: 'Diagnosis',
			ParentCodeValue: 'Colonoscopy',
			OrderingIndex: 5,
		},
		{
			Id: 507,
			Label: 'External piles (外痔)',
			Value: 'External piles (外痔)',
			CodeName: 'Diagnosis',
			ParentCodeValue: 'Colonoscopy',
			OrderingIndex: 6,
		},
		{
			Id: 508,
			Label: 'Colitis (結腸炎)',
			Value: 'Colitis (結腸炎)',
			CodeName: 'Diagnosis',
			ParentCodeValue: 'Colonoscopy',
			OrderingIndex: 7,
		},
		{
			Id: 509,
			Label: 'Diverticulosis of colon (憩室)',
			Value: 'Diverticulosis of colon (憩室)',
			CodeName: 'Diagnosis',
			ParentCodeValue: 'Colonoscopy',
			OrderingIndex: 8,
		},
		{
			Id: 510,
			Label: 'Duverucyka (憩室)',
			Value: 'Duverucyka (憩室)',
			CodeName: 'Diagnosis',
			ParentCodeValue: 'Colonoscopy',
			OrderingIndex: 9,
		},
		{
			Id: 511,
			Label: 'Diverticulitis (憩室炎)',
			Value: 'Diverticulitis (憩室炎)',
			CodeName: 'Diagnosis',
			ParentCodeValue: 'Colonoscopy',
			OrderingIndex: 10,
		},
		{
			Id: 512,
			Label: 'Fistula-in-ano (瘻管 肛瘺)',
			Value: 'Fistula-in-ano (瘻管 肛瘺)',
			CodeName: 'Diagnosis',
			ParentCodeValue: 'Colonoscopy',
			OrderingIndex: 11,
		},
		{
			Id: 513,
			Label: 'Normal (正常)',
			Value: 'Normal (正常)',
			CodeName: 'Diagnosis',
			ParentCodeValue: 'Colonoscopy',
			OrderingIndex: 12,
		},
		{
			Id: 514,
			Label: 'Pruritis ani',
			Value: 'Pruritis ani',
			CodeName: 'Diagnosis',
			ParentCodeValue: 'Colonoscopy',
			OrderingIndex: 13,
		},
		{
			Id: 515,
			Label: 'Ulcerative colitis (潰瘍性結腸炎)',
			Value: 'Ulcerative colitis (潰瘍性結腸炎)',
			CodeName: 'Diagnosis',
			ParentCodeValue: 'Colonoscopy',
			OrderingIndex: 14,
		},
		{
			Id: 516,
			Label: "Crohn's disease (克隆氏病變)",
			Value: "Crohn's disease (克隆氏病變)",
			CodeName: 'Diagnosis',
			ParentCodeValue: 'Colonoscopy',
			OrderingIndex: 15,
		},
		{
			Id: 517,
			Label: 'Diverticulosis (憩室)',
			Value: 'Diverticulosis (憩室)',
			CodeName: 'Diagnosis',
			ParentCodeValue: 'Colonoscopy',
			OrderingIndex: 16,
		},
		{
			Id: 518,
			Label: 'Diverticulum (憩室)',
			Value: 'Diverticulum (憩室)',
			CodeName: 'Diagnosis',
			ParentCodeValue: 'Colonoscopy',
			OrderingIndex: 17,
		},
		{
			Id: 519,
			Label: 'Melanosis Coli',
			Value: 'Melanosis Coli',
			CodeName: 'Diagnosis',
			ParentCodeValue: 'Colonoscopy',
			OrderingIndex: 18,
		},
		{
			Id: 520,
			Label: 'Polypectomy site bleeding',
			Value: 'Polypectomy site bleeding',
			CodeName: 'Diagnosis',
			ParentCodeValue: 'Colonoscopy',
			OrderingIndex: 19,
		},
		{
			Id: 521,
			Label: 'Proctitis',
			Value: 'Proctitis',
			CodeName: 'Diagnosis',
			ParentCodeValue: 'Colonoscopy',
			OrderingIndex: 20,
		},
		{
			Id: 522,
			Label: 'Submucosal lesion',
			Value: 'Submucosal lesion',
			CodeName: 'Diagnosis',
			ParentCodeValue: 'Colonoscopy',
			OrderingIndex: 21,
		},
		{
			Id: 523,
			Label: 'Tumour',
			Value: 'Tumour',
			CodeName: 'Diagnosis',
			ParentCodeValue: 'Colonoscopy',
			OrderingIndex: 22,
		},
		{
			Id: 524,
			Label: 'Suspected colonic cancer',
			Value: 'Suspected colonic cancer',
			CodeName: 'Diagnosis',
			ParentCodeValue: 'Colonoscopy',
			OrderingIndex: 23,
		},
		{
			Id: 721,
			Label: 'Cystitis',
			Value: 'Cystitis',
			CodeName: 'Diagnosis',
			ParentCodeValue: 'Cystoscopy',
			OrderingIndex: 1,
		},
		{
			Id: 722,
			Label: 'Haematuria',
			Value: 'Haematuria',
			CodeName: 'Diagnosis',
			ParentCodeValue: 'Cystoscopy',
			OrderingIndex: 2,
		},
		{
			Id: 302,
			Label: 'Gastritis (胃炎)',
			Value: 'Gastritis (胃炎)',
			CodeName: 'Diagnosis',
			ParentCodeValue: 'Gastroscopy',
			OrderingIndex: 1,
		},
		{
			Id: 303,
			Label: 'Duodenitis (十二指腸炎)',
			Value: 'Duodenitis (十二指腸炎)',
			CodeName: 'Diagnosis',
			ParentCodeValue: 'Gastroscopy',
			OrderingIndex: 2,
		},
		{
			Id: 304,
			Label: 'Oesophagitis (食道炎)',
			Value: 'Oesophagitis (食道炎)',
			CodeName: 'Diagnosis',
			ParentCodeValue: 'Gastroscopy',
			OrderingIndex: 3,
		},
		{
			Id: 305,
			Label: 'Gastric polyp(s) (胃瘜肉)',
			Value: 'Gastric polyp(s) (胃瘜肉)',
			CodeName: 'Diagnosis',
			ParentCodeValue: 'Gastroscopy',
			OrderingIndex: 4,
		},
		{
			Id: 306,
			Label: 'Duodenal polyp ( 十二指腸瘜肉 )',
			Value: 'Duodenal polyp ( 十二指腸瘜肉 )',
			CodeName: 'Diagnosis',
			ParentCodeValue: 'Gastroscopy',
			OrderingIndex: 5,
		},
		{
			Id: 307,
			Label: 'Oesophageal polyp (食道瘜肉)',
			Value: 'Oesophageal polyp (食道瘜肉)',
			CodeName: 'Diagnosis',
			ParentCodeValue: 'Gastroscopy',
			OrderingIndex: 6,
		},
		{
			Id: 308,
			Label: 'Gastric erosion (胃部糜爛)',
			Value: 'Gastric erosion (胃部糜爛)',
			CodeName: 'Diagnosis',
			ParentCodeValue: 'Gastroscopy',
			OrderingIndex: 7,
		},
		{
			Id: 309,
			Label: 'Gastric ulcer (胃潰瘍)',
			Value: 'Gastric ulcer (胃潰瘍)',
			CodeName: 'Diagnosis',
			ParentCodeValue: 'Gastroscopy',
			OrderingIndex: 8,
		},
		{
			Id: 310,
			Label: 'Gastric tumour (胃腫瘤)',
			Value: 'Gastric tumour (胃腫瘤)',
			CodeName: 'Diagnosis',
			ParentCodeValue: 'Gastroscopy',
			OrderingIndex: 9,
		},
		{
			Id: 311,
			Label: 'Fundic gland polyp (s) (胃底腺瘜肉)',
			Value: 'Fundic gland polyp (s) (胃底腺瘜肉)',
			CodeName: 'Diagnosis',
			ParentCodeValue: 'Gastroscopy',
			OrderingIndex: 10,
		},
		{
			Id: 312,
			Label: 'Atrophic gastritis (萎縮性胃炎)',
			Value: 'Atrophic gastritis (萎縮性胃炎)',
			CodeName: 'Diagnosis',
			ParentCodeValue: 'Gastroscopy',
			OrderingIndex: 11,
		},
		{
			Id: 313,
			Label: 'Gastric submucosal mass (胃黏膜下層腫物',
			Value: 'Gastric submucosal mass (胃黏膜下層腫物',
			CodeName: 'Diagnosis',
			ParentCodeValue: 'Gastroscopy',
			OrderingIndex: 12,
		},
		{
			Id: 314,
			Label: 'Gastric varices (胃部靜脈曲張)',
			Value: 'Gastric varices (胃部靜脈曲張)',
			CodeName: 'Diagnosis',
			ParentCodeValue: 'Gastroscopy',
			OrderingIndex: 13,
		},
		{
			Id: 315,
			Label: 'Healed ulcer (已痊癒的潰瘍)',
			Value: 'Healed ulcer (已痊癒的潰瘍)',
			CodeName: 'Diagnosis',
			ParentCodeValue: 'Gastroscopy',
			OrderingIndex: 14,
		},
		{
			Id: 316,
			Label: 'Portal hypertensive gastropathy',
			Value: 'Portal hypertensive gastropathy',
			CodeName: 'Diagnosis',
			ParentCodeValue: 'Gastroscopy',
			OrderingIndex: 15,
		},
		{
			Id: 317,
			Label: 'Pyloric stenosis (幽門狹窄)',
			Value: 'Pyloric stenosis (幽門狹窄)',
			CodeName: 'Diagnosis',
			ParentCodeValue: 'Gastroscopy',
			OrderingIndex: 16,
		},
		{
			Id: 318,
			Label: 'Duondenal erosion ( 十二指腸糜爛 )',
			Value: 'Duondenal erosion ( 十二指腸糜爛 )',
			CodeName: 'Diagnosis',
			ParentCodeValue: 'Gastroscopy',
			OrderingIndex: 17,
		},
		{
			Id: 319,
			Label: 'Duodenal ulcer ( 十二指腸潰瘍 )',
			Value: 'Duodenal ulcer ( 十二指腸潰瘍 )',
			CodeName: 'Diagnosis',
			ParentCodeValue: 'Gastroscopy',
			OrderingIndex: 18,
		},
		{
			Id: 320,
			Label: 'Hiatus hernia (食道裂孔疝氣)',
			Value: 'Hiatus hernia (食道裂孔疝氣)',
			CodeName: 'Diagnosis',
			ParentCodeValue: 'Gastroscopy',
			OrderingIndex: 19,
		},
		{
			Id: 643,
			Label: 'Acute Gastritis (急性胃炎)',
			Value: 'Acute Gastritis (急性胃炎)',
			CodeName: 'Diagnosis',
			ParentCodeValue: 'Gastroscopy',
			OrderingIndex: 19,
		},
		{
			Id: 321,
			Label: 'Mallory-Weiss tear (胃食道接口裂)',
			Value: 'Mallory-Weiss tear (胃食道接口裂)',
			CodeName: 'Diagnosis',
			ParentCodeValue: 'Gastroscopy',
			OrderingIndex: 20,
		},
		{
			Id: 322,
			Label: 'Achalasia (食道弛緩不能)',
			Value: 'Achalasia (食道弛緩不能)',
			CodeName: 'Diagnosis',
			ParentCodeValue: 'Gastroscopy',
			OrderingIndex: 21,
		},
		{
			Id: 323,
			Label: "Suspected Barrett's oesophagus (",
			Value: "Barrett's oesophagus (巴洛氏食管病變)",
			CodeName: 'Diagnosis',
			ParentCodeValue: 'Gastroscopy',
			OrderingIndex: 22,
		},
		{
			Id: 324,
			Label: 'Benign oesophageal stricture (良性',
			Value: 'Benign oesophageal stricture (良性',
			CodeName: 'Diagnosis',
			ParentCodeValue: 'Gastroscopy',
			OrderingIndex: 23,
		},
		{
			Id: 325,
			Label: 'Erosive oesophagitis (糜爛性食道炎)',
			Value: 'Erosive oesophagitis (糜爛性食道炎)',
			CodeName: 'Diagnosis',
			ParentCodeValue: 'Gastroscopy',
			OrderingIndex: 24,
		},
		{
			Id: 326,
			Label: 'Oesophageal fistula (食道瘺管)',
			Value: 'Oesophageal fistula (食道瘺管)',
			CodeName: 'Diagnosis',
			ParentCodeValue: 'Gastroscopy',
			OrderingIndex: 25,
		},
		{
			Id: 327,
			Label: 'Oesophageal submucosal mass (食道黏',
			Value: 'Oesophageal submucosal mass (食道黏',
			CodeName: 'Diagnosis',
			ParentCodeValue: 'Gastroscopy',
			OrderingIndex: 26,
		},
		{
			Id: 328,
			Label: 'Oesophageal tumour (食道腫瘤)',
			Value: 'Oesophageal tumour (食道腫瘤)',
			CodeName: 'Diagnosis',
			ParentCodeValue: 'Gastroscopy',
			OrderingIndex: 27,
		},
		{
			Id: 329,
			Label: 'Oesophageal varices (食道靜脈曲張)',
			Value: 'Oesophageal varices (食道靜脈曲張)',
			CodeName: 'Diagnosis',
			ParentCodeValue: 'Gastroscopy',
			OrderingIndex: 28,
		},
		{
			Id: 330,
			Label: 'Foreign body (異物)',
			Value: 'Foreign body (異物)',
			CodeName: 'Diagnosis',
			ParentCodeValue: 'Gastroscopy',
			OrderingIndex: 29,
		},
		{
			Id: 331,
			Label: 'Normal',
			Value: 'Normal',
			CodeName: 'Diagnosis',
			ParentCodeValue: 'Gastroscopy',
			OrderingIndex: 30,
		},
		{
			Id: 332,
			Label: 'Diverticulum ( 憩室 )',
			Value: 'Diverticulum ( 憩室 )',
			CodeName: 'Diagnosis',
			ParentCodeValue: 'Gastroscopy',
			OrderingIndex: 31,
		},
		{
			Id: 693,
			Label: 'Helicobacter gastritis (幽門螺旋菌胃炎)',
			Value: 'Helicobacter gastritis(幽門螺旋菌胃炎)',
			CodeName: 'Diagnosis',
			ParentCodeValue: 'Gastroscopy',
			OrderingIndex: 32,
		},
	],
	Doctor: [
		{
			Id: 618,
			Label: 'Dr. Chan Wai Hong Alvin',
			Value: 'Chan Wai Hong',
			CodeName: 'Doctor',
			ParentCodeValue: '',
			OrderingIndex: 1,
		},
		{
			Id: 619,
			Label: 'Dr. Choi Tat Fai Richard',
			Value: 'Choi Tat Fai Richard',
			CodeName: 'Doctor',
			ParentCodeValue: '',
			OrderingIndex: 2,
		},
	],
	Dosage: [
		{
			Id: 641,
			Label: 'mg',
			Value: 'mg',
			CodeName: 'Dosage',
			ParentCodeValue: '',
			OrderingIndex: 1,
		},
		{
			Id: 642,
			Label: 'mcg',
			Value: 'mcg',
			CodeName: 'Dosage',
			ParentCodeValue: '',
			OrderingIndex: 2,
		},
	],
	History: [
		{
			Id: 333,
			Label: 'History of benign prostate hyper',
			Value: 'History of benign prostate hyper',
			CodeName: 'History',
			ParentCodeValue: '',
			OrderingIndex: 1,
		},
		{
			Id: 334,
			Label: 'Family history of gastric cancer',
			Value: 'Family history of gastric cancer',
			CodeName: 'History',
			ParentCodeValue: '',
			OrderingIndex: 2,
		},
		{
			Id: 335,
			Label: 'Family history of colorectal can',
			Value: 'Family history of colorectal can',
			CodeName: 'History',
			ParentCodeValue: '',
			OrderingIndex: 3,
		},
		{
			Id: 336,
			Label: 'Personal history of gastric canc',
			Value: 'Personal history of gastric canc',
			CodeName: 'History',
			ParentCodeValue: '',
			OrderingIndex: 4,
		},
		{
			Id: 337,
			Label: 'Personal history of colorectal c',
			Value: 'Personal history of colorectal c',
			CodeName: 'History',
			ParentCodeValue: '',
			OrderingIndex: 5,
		},
		{
			Id: 338,
			Label: 'Family History',
			Value: 'Family History',
			CodeName: 'History',
			ParentCodeValue: '',
			OrderingIndex: 6,
		},
	],
	ImageFindings: [
		{
			Id: 200,
			Label: 'Polyp',
			Value: 'Polyp',
			CodeName: 'ImageFindings',
			ParentCodeValue: 'Colonoscopy',
			OrderingIndex: 1,
		},
		{
			Id: 201,
			Label: 'Lateral Spreading tumor',
			Value: 'Lateral Spreading tumor',
			CodeName: 'ImageFindings',
			ParentCodeValue: 'Colonoscopy',
			OrderingIndex: 2,
		},
		{
			Id: 202,
			Label: 'Colitis',
			Value: 'Colitis',
			CodeName: 'ImageFindings',
			ParentCodeValue: 'Colonoscopy',
			OrderingIndex: 3,
		},
		{
			Id: 203,
			Label: 'Diverticulum',
			Value: 'Diverticulum',
			CodeName: 'ImageFindings',
			ParentCodeValue: 'Colonoscopy',
			OrderingIndex: 4,
		},
		{
			Id: 204,
			Label: 'Haemorrhoid',
			Value: 'Haemorrhoid',
			CodeName: 'ImageFindings',
			ParentCodeValue: 'Colonoscopy',
			OrderingIndex: 5,
		},
		{
			Id: 205,
			Label: 'Anal fissure',
			Value: 'Anal fissure',
			CodeName: 'ImageFindings',
			ParentCodeValue: 'Colonoscopy',
			OrderingIndex: 6,
		},
		{
			Id: 206,
			Label: 'Anal skin tag',
			Value: 'Anal skin tag',
			CodeName: 'ImageFindings',
			ParentCodeValue: 'Colonoscopy',
			OrderingIndex: 7,
		},
		{
			Id: 207,
			Label: 'Angioectasia',
			Value: 'Angioectasia',
			CodeName: 'ImageFindings',
			ParentCodeValue: 'Colonoscopy',
			OrderingIndex: 8,
		},
		{
			Id: 208,
			Label: 'Scar',
			Value: 'Scar',
			CodeName: 'ImageFindings',
			ParentCodeValue: 'Colonoscopy',
			OrderingIndex: 9,
		},
		{
			Id: 209,
			Label: 'Polypectomy site',
			Value: 'Polypectomy site',
			CodeName: 'ImageFindings',
			ParentCodeValue: 'Colonoscopy',
			OrderingIndex: 10,
		},
		{
			Id: 210,
			Label: 'Condylomas',
			Value: 'Condylomas',
			CodeName: 'ImageFindings',
			ParentCodeValue: 'Colonoscopy',
			OrderingIndex: 11,
		},
		{
			Id: 211,
			Label: 'Erosion',
			Value: 'Erosion',
			CodeName: 'ImageFindings',
			ParentCodeValue: 'Colonoscopy',
			OrderingIndex: 12,
		},
		{
			Id: 212,
			Label: 'Erythematous (Hypermic)',
			Value: 'Erythematous (Hypermic)',
			CodeName: 'ImageFindings',
			ParentCodeValue: 'Colonoscopy',
			OrderingIndex: 13,
		},
		{
			Id: 213,
			Label: 'Evidence of previous surgery',
			Value: 'Evidence of previous surgery',
			CodeName: 'ImageFindings',
			ParentCodeValue: 'Colonoscopy',
			OrderingIndex: 14,
		},
		{
			Id: 214,
			Label: 'Excavated lesion',
			Value: 'Excavated lesion',
			CodeName: 'ImageFindings',
			ParentCodeValue: 'Colonoscopy',
			OrderingIndex: 15,
		},
		{
			Id: 215,
			Label: 'Exudate',
			Value: 'Exudate',
			CodeName: 'ImageFindings',
			ParentCodeValue: 'Colonoscopy',
			OrderingIndex: 16,
		},
		{
			Id: 216,
			Label: 'Fistula',
			Value: 'Fistula',
			CodeName: 'ImageFindings',
			ParentCodeValue: 'Colonoscopy',
			OrderingIndex: 17,
		},
		{
			Id: 217,
			Label: 'Foreign body',
			Value: 'Foreign body',
			CodeName: 'ImageFindings',
			ParentCodeValue: 'Colonoscopy',
			OrderingIndex: 18,
		},
		{
			Id: 218,
			Label: 'Colonic lipoma',
			Value: 'Colonic lipoma',
			CodeName: 'ImageFindings',
			ParentCodeValue: 'Colonoscopy',
			OrderingIndex: 19,
		},
		{
			Id: 219,
			Label: 'Melanosis coli',
			Value: 'Melanosis coli',
			CodeName: 'ImageFindings',
			ParentCodeValue: 'Colonoscopy',
			OrderingIndex: 20,
		},
		{
			Id: 220,
			Label: 'NBI image',
			Value: 'NBI image',
			CodeName: 'ImageFindings',
			ParentCodeValue: 'Colonoscopy',
			OrderingIndex: 21,
		},
		{
			Id: 221,
			Label: 'Polypectomy site, post cauterisa',
			Value: 'Polypectomy site, post cauterisa',
			CodeName: 'ImageFindings',
			ParentCodeValue: 'Colonoscopy',
			OrderingIndex: 22,
		},
		{
			Id: 222,
			Label: 'Pseudomembrance',
			Value: 'Pseudomembrance',
			CodeName: 'ImageFindings',
			ParentCodeValue: 'Colonoscopy',
			OrderingIndex: 23,
		},
		{
			Id: 223,
			Label: 'Pseudopolyp',
			Value: 'Pseudopolyp',
			CodeName: 'ImageFindings',
			ParentCodeValue: 'Colonoscopy',
			OrderingIndex: 24,
		},
		{
			Id: 224,
			Label: 'Pseudopolyps',
			Value: 'Pseudopolyps',
			CodeName: 'ImageFindings',
			ParentCodeValue: 'Colonoscopy',
			OrderingIndex: 25,
		},
		{
			Id: 225,
			Label: 'Stenosis',
			Value: 'Stenosis',
			CodeName: 'ImageFindings',
			ParentCodeValue: 'Colonoscopy',
			OrderingIndex: 26,
		},
		{
			Id: 226,
			Label: 'Stent',
			Value: 'Stent',
			CodeName: 'ImageFindings',
			ParentCodeValue: 'Colonoscopy',
			OrderingIndex: 27,
		},
		{
			Id: 227,
			Label: 'Submucosal mass',
			Value: 'Submucosal mass',
			CodeName: 'ImageFindings',
			ParentCodeValue: 'Colonoscopy',
			OrderingIndex: 28,
		},
		{
			Id: 228,
			Label: 'Suture granuloma',
			Value: 'Suture granuloma',
			CodeName: 'ImageFindings',
			ParentCodeValue: 'Colonoscopy',
			OrderingIndex: 29,
		},
		{
			Id: 229,
			Label: 'Tumour',
			Value: 'Tumour',
			CodeName: 'ImageFindings',
			ParentCodeValue: 'Colonoscopy',
			OrderingIndex: 30,
		},
		{
			Id: 230,
			Label: 'Ulcer',
			Value: 'Ulcer',
			CodeName: 'ImageFindings',
			ParentCodeValue: 'Colonoscopy',
			OrderingIndex: 31,
		},
		{
			Id: 231,
			Label: 'Ulerative mucosa',
			Value: 'Ulerative mucosa',
			CodeName: 'ImageFindings',
			ParentCodeValue: 'Colonoscopy',
			OrderingIndex: 32,
		},
		{
			Id: 704,
			Label: 'Polpy bx',
			Value: 'Polyp bx',
			CodeName: 'ImageFindings',
			ParentCodeValue: 'Colonoscopy',
			OrderingIndex: 33,
		},
		{
			Id: 232,
			Label: 'Gastritis',
			Value: 'Gastritis',
			CodeName: 'ImageFindings',
			ParentCodeValue: 'Gastroscopy',
			OrderingIndex: 1,
		},
		{
			Id: 233,
			Label: 'Duodenitis',
			Value: 'Duodenitis',
			CodeName: 'ImageFindings',
			ParentCodeValue: 'Gastroscopy',
			OrderingIndex: 2,
		},
		{
			Id: 234,
			Label: 'Esophagitis',
			Value: 'Esophagitis',
			CodeName: 'ImageFindings',
			ParentCodeValue: 'Gastroscopy',
			OrderingIndex: 3,
		},
		{
			Id: 235,
			Label: 'Erosion',
			Value: 'Erosion',
			CodeName: 'ImageFindings',
			ParentCodeValue: 'Gastroscopy',
			OrderingIndex: 4,
		},
		{
			Id: 236,
			Label: 'Ulcer',
			Value: 'Ulcer',
			CodeName: 'ImageFindings',
			ParentCodeValue: 'Gastroscopy',
			OrderingIndex: 5,
		},
		{
			Id: 237,
			Label: 'Polyp',
			Value: 'Polyp',
			CodeName: 'ImageFindings',
			ParentCodeValue: 'Gastroscopy',
			OrderingIndex: 6,
		},
		{
			Id: 238,
			Label: 'Hiatus Hernia',
			Value: 'Hiatus Hernia',
			CodeName: 'ImageFindings',
			ParentCodeValue: 'Gastroscopy',
			OrderingIndex: 7,
		},
		{
			Id: 239,
			Label: 'Varices',
			Value: 'Varices',
			CodeName: 'ImageFindings',
			ParentCodeValue: 'Gastroscopy',
			OrderingIndex: 8,
		},
		{
			Id: 240,
			Label: 'Angioectasia',
			Value: 'Angioectasia',
			CodeName: 'ImageFindings',
			ParentCodeValue: 'Gastroscopy',
			OrderingIndex: 9,
		},
		{
			Id: 241,
			Label: 'Atrophic Gastritis',
			Value: 'Atrophic Gastritis',
			CodeName: 'ImageFindings',
			ParentCodeValue: 'Gastroscopy',
			OrderingIndex: 10,
		},
		{
			Id: 242,
			Label: "Barrett's Esophagus",
			Value: "Barrett's Esophagus",
			CodeName: 'ImageFindings',
			ParentCodeValue: 'Gastroscopy',
			OrderingIndex: 11,
		},
		{
			Id: 243,
			Label: 'Candidiasis',
			Value: 'Candidiasis',
			CodeName: 'ImageFindings',
			ParentCodeValue: 'Gastroscopy',
			OrderingIndex: 12,
		},
		{
			Id: 244,
			Label: 'Deformity',
			Value: 'Deformity',
			CodeName: 'ImageFindings',
			ParentCodeValue: 'Gastroscopy',
			OrderingIndex: 13,
		},
		{
			Id: 245,
			Label: 'Pyloric stenosis',
			Value: 'Pyloric stenosis',
			CodeName: 'ImageFindings',
			ParentCodeValue: 'Gastroscopy',
			OrderingIndex: 14,
		},
		{
			Id: 246,
			Label: 'Dieulafoy lesion',
			Value: 'Dieulafoy lesion',
			CodeName: 'ImageFindings',
			ParentCodeValue: 'Gastroscopy',
			OrderingIndex: 15,
		},
		{
			Id: 247,
			Label: 'Diverticulum',
			Value: 'Diverticulum',
			CodeName: 'ImageFindings',
			ParentCodeValue: 'Gastroscopy',
			OrderingIndex: 16,
		},
		{
			Id: 248,
			Label: 'Evidence of previous surgery',
			Value: 'Evidence of previous surgery',
			CodeName: 'ImageFindings',
			ParentCodeValue: 'Gastroscopy',
			OrderingIndex: 17,
		},
		{
			Id: 249,
			Label: 'Extrinsic compression',
			Value: 'Extrinsic compression',
			CodeName: 'ImageFindings',
			ParentCodeValue: 'Gastroscopy',
			OrderingIndex: 18,
		},
		{
			Id: 250,
			Label: 'Flat lesions',
			Value: 'Flat lesions',
			CodeName: 'ImageFindings',
			ParentCodeValue: 'Gastroscopy',
			OrderingIndex: 19,
		},
		{
			Id: 251,
			Label: 'Foreign Body',
			Value: 'Foreign Body',
			CodeName: 'ImageFindings',
			ParentCodeValue: 'Gastroscopy',
			OrderingIndex: 20,
		},
		{
			Id: 252,
			Label: 'Lipoma',
			Value: 'Lipoma',
			CodeName: 'ImageFindings',
			ParentCodeValue: 'Gastroscopy',
			OrderingIndex: 21,
		},
		{
			Id: 253,
			Label: 'Mallory-Weiss tear',
			Value: 'Mallory-Weiss tear',
			CodeName: 'ImageFindings',
			ParentCodeValue: 'Gastroscopy',
			OrderingIndex: 22,
		},
		{
			Id: 254,
			Label: 'NBI image',
			Value: 'NBI image',
			CodeName: 'ImageFindings',
			ParentCodeValue: 'Gastroscopy',
			OrderingIndex: 23,
		},
		{
			Id: 255,
			Label: 'Scar',
			Value: 'Scar',
			CodeName: 'ImageFindings',
			ParentCodeValue: 'Gastroscopy',
			OrderingIndex: 24,
		},
		{
			Id: 256,
			Label: 'Stricture',
			Value: 'Stricture',
			CodeName: 'ImageFindings',
			ParentCodeValue: 'Gastroscopy',
			OrderingIndex: 25,
		},
		{
			Id: 257,
			Label: 'Submucosal mass',
			Value: 'Submucosal mass',
			CodeName: 'ImageFindings',
			ParentCodeValue: 'Gastroscopy',
			OrderingIndex: 26,
		},
		{
			Id: 258,
			Label: 'Tongue like extensions',
			Value: 'Tongue like extensions',
			CodeName: 'ImageFindings',
			ParentCodeValue: 'Gastroscopy',
			OrderingIndex: 27,
		},
		{
			Id: 259,
			Label: 'Tumour',
			Value: 'Tumour',
			CodeName: 'ImageFindings',
			ParentCodeValue: 'Gastroscopy',
			OrderingIndex: 28,
		},
		{
			Id: 705,
			Label: 'Polyp bx',
			Value: 'Polyp bx',
			CodeName: 'ImageFindings',
			ParentCodeValue: 'Gastroscopy',
			OrderingIndex: 29,
		},
	],
	ImageSites: [
		{
			Id: 281,
			Label: 'Anal canal',
			Value: 'Anal canal',
			CodeName: 'ImageSites',
			ParentCodeValue: 'Colonoscopy',
			OrderingIndex: 1,
		},
		{
			Id: 282,
			Label: 'Anastomosis',
			Value: 'Anastomosis',
			CodeName: 'ImageSites',
			ParentCodeValue: 'Colonoscopy',
			OrderingIndex: 2,
		},
		{
			Id: 283,
			Label: 'Anus',
			Value: 'Anus',
			CodeName: 'ImageSites',
			ParentCodeValue: 'Colonoscopy',
			OrderingIndex: 3,
		},
		{
			Id: 284,
			Label: 'Appendiceal opening',
			Value: 'Appendiceal opening',
			CodeName: 'ImageSites',
			ParentCodeValue: 'Colonoscopy',
			OrderingIndex: 4,
		},
		{
			Id: 285,
			Label: 'Appendiceal orifice and caeum',
			Value: 'Appendiceal orifice and caeum',
			CodeName: 'ImageSites',
			ParentCodeValue: 'Colonoscopy',
			OrderingIndex: 5,
		},
		{
			Id: 286,
			Label: 'Ascending colon',
			Value: 'Ascending colon',
			CodeName: 'ImageSites',
			ParentCodeValue: 'Colonoscopy',
			OrderingIndex: 6,
		},
		{
			Id: 287,
			Label: 'Caecum',
			Value: 'Caecum',
			CodeName: 'ImageSites',
			ParentCodeValue: 'Colonoscopy',
			OrderingIndex: 7,
		},
		{
			Id: 288,
			Label: 'Descending colon',
			Value: 'Descending colon',
			CodeName: 'ImageSites',
			ParentCodeValue: 'Colonoscopy',
			OrderingIndex: 8,
		},
		{
			Id: 289,
			Label: 'Hepatic flexure',
			Value: 'Hepatic flexure',
			CodeName: 'ImageSites',
			ParentCodeValue: 'Colonoscopy',
			OrderingIndex: 9,
		},
		{
			Id: 290,
			Label: 'lleo-caecal valve',
			Value: 'lleo-caecal valve',
			CodeName: 'ImageSites',
			ParentCodeValue: 'Colonoscopy',
			OrderingIndex: 10,
		},
		{
			Id: 291,
			Label: 'Ileum',
			Value: 'Ileum',
			CodeName: 'ImageSites',
			ParentCodeValue: 'Colonoscopy',
			OrderingIndex: 11,
		},
		{
			Id: 292,
			Label: 'Lower rectum',
			Value: 'Lower rectum',
			CodeName: 'ImageSites',
			ParentCodeValue: 'Colonoscopy',
			OrderingIndex: 12,
		},
		{
			Id: 293,
			Label: 'Rectosigmoid',
			Value: 'Rectosigmoid',
			CodeName: 'ImageSites',
			ParentCodeValue: 'Colonoscopy',
			OrderingIndex: 13,
		},
		{
			Id: 294,
			Label: 'Rectum',
			Value: 'Rectum',
			CodeName: 'ImageSites',
			ParentCodeValue: 'Colonoscopy',
			OrderingIndex: 14,
		},
		{
			Id: 295,
			Label: 'Retroflexion and inside view of',
			Value: 'Retroflexion and inside view of',
			CodeName: 'ImageSites',
			ParentCodeValue: 'Colonoscopy',
			OrderingIndex: 15,
		},
		{
			Id: 296,
			Label: 'Sigmoid colon',
			Value: 'Sigmoid colon',
			CodeName: 'ImageSites',
			ParentCodeValue: 'Colonoscopy',
			OrderingIndex: 16,
		},
		{
			Id: 297,
			Label: 'Splenic flexure',
			Value: 'Splenic flexure',
			CodeName: 'ImageSites',
			ParentCodeValue: 'Colonoscopy',
			OrderingIndex: 17,
		},
		{
			Id: 298,
			Label: 'Stoma',
			Value: 'Stoma',
			CodeName: 'ImageSites',
			ParentCodeValue: 'Colonoscopy',
			OrderingIndex: 18,
		},
		{
			Id: 299,
			Label: 'Terminal ileum',
			Value: 'Terminal ileum',
			CodeName: 'ImageSites',
			ParentCodeValue: 'Colonoscopy',
			OrderingIndex: 19,
		},
		{
			Id: 300,
			Label: 'Transverse colon',
			Value: 'Transverse colon',
			CodeName: 'ImageSites',
			ParentCodeValue: 'Colonoscopy',
			OrderingIndex: 20,
		},
		{
			Id: 301,
			Label: 'Ileo-colic anastomsis',
			Value: 'Ileo-colic anastomsis',
			CodeName: 'ImageSites',
			ParentCodeValue: 'Colonoscopy',
			OrderingIndex: 21,
		},
		{
			Id: 706,
			Label: 'Left UO',
			Value: 'Left Uo',
			CodeName: 'ImageSites',
			ParentCodeValue: 'Cystoscopy',
			OrderingIndex: 1,
		},
		{
			Id: 707,
			Label: 'Right UO',
			Value: 'Right Uo',
			CodeName: 'ImageSites',
			ParentCodeValue: 'Cystoscopy',
			OrderingIndex: 2,
		},
		{
			Id: 708,
			Label: 'Bladder Base',
			Value: 'Bladder Base',
			CodeName: 'ImageSites',
			ParentCodeValue: 'Cystoscopy',
			OrderingIndex: 3,
		},
		{
			Id: 709,
			Label: 'Old TURBT Scar',
			Value: 'Old TURBT Scar',
			CodeName: 'ImageSites',
			ParentCodeValue: 'Cystoscopy',
			OrderingIndex: 4,
		},
		{
			Id: 710,
			Label: 'Trigone',
			Value: 'Trigone',
			CodeName: 'ImageSites',
			ParentCodeValue: 'Cystoscopy',
			OrderingIndex: 5,
		},
		{
			Id: 711,
			Label: 'Left Lateral Wall',
			Value: 'Left Lateral Wall',
			CodeName: 'ImageSites',
			ParentCodeValue: 'Cystoscopy',
			OrderingIndex: 6,
		},
		{
			Id: 712,
			Label: 'Anterior Wall',
			Value: 'Anterior Wall',
			CodeName: 'ImageSites',
			ParentCodeValue: 'Cystoscopy',
			OrderingIndex: 7,
		},
		{
			Id: 713,
			Label: 'Right Lateral Wall',
			Value: 'Right Lateral Wall',
			CodeName: 'ImageSites',
			ParentCodeValue: 'Cystoscopy',
			OrderingIndex: 8,
		},
		{
			Id: 714,
			Label: 'Bladder Neck',
			Value: 'Bladder Neck',
			CodeName: 'ImageSites',
			ParentCodeValue: 'Cystoscopy',
			OrderingIndex: 9,
		},
		{
			Id: 645,
			Label: 'D3',
			Value: 'D3',
			CodeName: 'ImageSites',
			ParentCodeValue: 'Gastroscopy',
			OrderingIndex: 1,
		},
		{
			Id: 646,
			Label: 'D2',
			Value: 'D2',
			CodeName: 'ImageSites',
			ParentCodeValue: 'Gastroscopy',
			OrderingIndex: 2,
		},
		{
			Id: 647,
			Label: 'D1',
			Value: 'D1',
			CodeName: 'ImageSites',
			ParentCodeValue: 'Gastroscopy',
			OrderingIndex: 3,
		},
		{
			Id: 648,
			Label: 'Antrum',
			Value: 'Antrum',
			CodeName: 'ImageSites',
			ParentCodeValue: 'Gastroscopy',
			OrderingIndex: 4,
		},
		{
			Id: 649,
			Label: 'Incisura',
			Value: 'Incisura',
			CodeName: 'ImageSites',
			ParentCodeValue: 'Gastroscopy',
			OrderingIndex: 5,
		},
		{
			Id: 650,
			Label: 'Body',
			Value: 'Body',
			CodeName: 'ImageSites',
			ParentCodeValue: 'Gastroscopy',
			OrderingIndex: 6,
		},
		{
			Id: 651,
			Label: 'Cardia',
			Value: 'Cardia',
			CodeName: 'ImageSites',
			ParentCodeValue: 'Gastroscopy',
			OrderingIndex: 7,
		},
		{
			Id: 652,
			Label: 'Fundus',
			Value: 'Fundus',
			CodeName: 'ImageSites',
			ParentCodeValue: 'Gastroscopy',
			OrderingIndex: 8,
		},
		{
			Id: 653,
			Label: 'OGJ',
			Value: 'OGJ',
			CodeName: 'ImageSites',
			ParentCodeValue: 'Gastroscopy',
			OrderingIndex: 9,
		},
		{
			Id: 654,
			Label: 'Lower Oesophagus',
			Value: 'Lower Oesophagus',
			CodeName: 'ImageSites',
			ParentCodeValue: 'Gastroscopy',
			OrderingIndex: 10,
		},
		{
			Id: 655,
			Label: 'Middle Oesophagus',
			Value: 'Middle Oesophagus',
			CodeName: 'ImageSites',
			ParentCodeValue: 'Gastroscopy',
			OrderingIndex: 11,
		},
		{
			Id: 656,
			Label: 'Upper Oesophagus',
			Value: 'Upper Oesophagus',
			CodeName: 'ImageSites',
			ParentCodeValue: 'Gastroscopy',
			OrderingIndex: 12,
		},
	],
	Indication: [
		{
			Id: 14,
			Label: 'Abdominal distress / pain',
			Value: 'Abdominal distress / pain',
			CodeName: 'Indication',
			ParentCodeValue: 'Colonoscopy',
			OrderingIndex: 1,
		},
		{
			Id: 15,
			Label: 'Per rectal bleeding',
			Value: 'Per rectal bleeding',
			CodeName: 'Indication',
			ParentCodeValue: 'Colonoscopy',
			OrderingIndex: 2,
		},
		{
			Id: 16,
			Label: 'Altered bowel habit',
			Value: 'Altered bowel habit',
			CodeName: 'Indication',
			ParentCodeValue: 'Colonoscopy',
			OrderingIndex: 3,
		},
		{
			Id: 17,
			Label: 'Diarrhoea',
			Value: 'Diarrhoea',
			CodeName: 'Indication',
			ParentCodeValue: 'Colonoscopy',
			OrderingIndex: 4,
		},
		{
			Id: 18,
			Label: 'Constipation',
			Value: 'Constipation',
			CodeName: 'Indication',
			ParentCodeValue: 'Colonoscopy',
			OrderingIndex: 5,
		},
		{
			Id: 19,
			Label: 'Anemia',
			Value: 'Anemia',
			CodeName: 'Indication',
			ParentCodeValue: 'Colonoscopy',
			OrderingIndex: 6,
		},
		{
			Id: 20,
			Label: 'Abnormal imaging',
			Value: 'Abnormal imaging',
			CodeName: 'Indication',
			ParentCodeValue: 'Colonoscopy',
			OrderingIndex: 7,
		},
		{
			Id: 21,
			Label: 'Raised tumor marker',
			Value: 'Raised tumor marker',
			CodeName: 'Indication',
			ParentCodeValue: 'Colonoscopy',
			OrderingIndex: 8,
		},
		{
			Id: 22,
			Label: 'Cancer surveillance',
			Value: 'Cancer surveillance',
			CodeName: 'Indication',
			ParentCodeValue: 'Colonoscopy',
			OrderingIndex: 9,
		},
		{
			Id: 23,
			Label: 'Melena',
			Value: 'Melena',
			CodeName: 'Indication',
			ParentCodeValue: 'Colonoscopy',
			OrderingIndex: 10,
		},
		{
			Id: 24,
			Label: 'Nausea / Vomiting',
			Value: 'Nausea / Vomiting',
			CodeName: 'Indication',
			ParentCodeValue: 'Colonoscopy',
			OrderingIndex: 11,
		},
		{
			Id: 25,
			Label: 'Positive fecal occult blood test',
			Value: 'Positive fecal occult blood test',
			CodeName: 'Indication',
			ParentCodeValue: 'Colonoscopy',
			OrderingIndex: 12,
		},
		{
			Id: 26,
			Label: 'Weight loss',
			Value: 'Weight loss',
			CodeName: 'Indication',
			ParentCodeValue: 'Colonoscopy',
			OrderingIndex: 13,
		},
		{
			Id: 27,
			Label: 'Inflammatory bowel disease follo',
			Value: 'Inflammatory bowel disease follo',
			CodeName: 'Indication',
			ParentCodeValue: 'Colonoscopy',
			OrderingIndex: 14,
		},
		{
			Id: 28,
			Label: 'Proctalgia',
			Value: 'Proctalgia',
			CodeName: 'Indication',
			ParentCodeValue: 'Colonoscopy',
			OrderingIndex: 15,
		},
		{
			Id: 29,
			Label: 'Suspected inflammatory bowel dis',
			Value: 'Suspected inflammatory bowel dis',
			CodeName: 'Indication',
			ParentCodeValue: 'Colonoscopy',
			OrderingIndex: 16,
		},
		{
			Id: 715,
			Label: 'Haematuria',
			Value: 'Haematuria',
			CodeName: 'Indication',
			ParentCodeValue: 'Cystoscopy',
			OrderingIndex: 1,
		},
		{
			Id: 716,
			Label: 'Cystitis',
			Value: 'Cystitis',
			CodeName: 'Indication',
			ParentCodeValue: 'Cystoscopy',
			OrderingIndex: 2,
		},
		{
			Id: 717,
			Label: 'Ca Bladder',
			Value: 'Ca Bladder',
			CodeName: 'Indication',
			ParentCodeValue: 'Cystoscopy',
			OrderingIndex: 3,
		},
		{
			Id: 718,
			Label: 'Post Operation Follow Up',
			Value: 'Post Operation Follow Up',
			CodeName: 'Indication',
			ParentCodeValue: 'Cystoscopy',
			OrderingIndex: 4,
		},
		{
			Id: 719,
			Label: 'TCC Bladder',
			Value: 'TCC Bladder',
			CodeName: 'Indication',
			ParentCodeValue: 'Cystoscopy',
			OrderingIndex: 5,
		},
		{
			Id: 720,
			Label: 'Post TURBT Follow Up',
			Value: 'Post TURBT Follow UP',
			CodeName: 'Indication',
			ParentCodeValue: 'Cystoscopy',
			OrderingIndex: 6,
		},
		{
			Id: 30,
			Label: 'Abdominal distress / pain',
			Value: 'Abdominal distress / pain',
			CodeName: 'Indication',
			ParentCodeValue: 'Gastroscopy',
			OrderingIndex: 1,
		},
		{
			Id: 31,
			Label: 'Anemia',
			Value: 'Anemia',
			CodeName: 'Indication',
			ParentCodeValue: 'Gastroscopy',
			OrderingIndex: 2,
		},
		{
			Id: 32,
			Label: 'Cancer surveillance',
			Value: 'Cancer surveillance',
			CodeName: 'Indication',
			ParentCodeValue: 'Gastroscopy',
			OrderingIndex: 3,
		},
		{
			Id: 33,
			Label: 'Chest pain',
			Value: 'Chest pain',
			CodeName: 'Indication',
			ParentCodeValue: 'Gastroscopy',
			OrderingIndex: 4,
		},
		{
			Id: 34,
			Label: 'Coffee ground vomiting',
			Value: 'Coffee ground vomiting',
			CodeName: 'Indication',
			ParentCodeValue: 'Gastroscopy',
			OrderingIndex: 5,
		},
		{
			Id: 35,
			Label: 'Dysphagia',
			Value: 'Dysphagia',
			CodeName: 'Indication',
			ParentCodeValue: 'Gastroscopy',
			OrderingIndex: 6,
		},
		{
			Id: 36,
			Label: 'Epigastric pain',
			Value: 'Epigastric pain',
			CodeName: 'Indication',
			ParentCodeValue: 'Gastroscopy',
			OrderingIndex: 7,
		},
		{
			Id: 37,
			Label: 'Haematemesis',
			Value: 'Haematemesis',
			CodeName: 'Indication',
			ParentCodeValue: 'Gastroscopy',
			OrderingIndex: 8,
		},
		{
			Id: 38,
			Label: 'Melena',
			Value: 'Melena',
			CodeName: 'Indication',
			ParentCodeValue: 'Gastroscopy',
			OrderingIndex: 9,
		},
		{
			Id: 51,
			Label: 'Ulcer follow up',
			Value: 'Ulcer follow up',
			CodeName: 'Indication',
			ParentCodeValue: 'Gastroscopy',
			OrderingIndex: 10,
		},
		{
			Id: 40,
			Label: 'Nausea / Vomiting',
			Value: 'Nausea / Vomiting',
			CodeName: 'Indication',
			ParentCodeValue: 'Gastroscopy',
			OrderingIndex: 11,
		},
		{
			Id: 41,
			Label: 'Positive fecal occult blood test',
			Value: 'Positive fecal occult blood test',
			CodeName: 'Indication',
			ParentCodeValue: 'Gastroscopy',
			OrderingIndex: 12,
		},
		{
			Id: 42,
			Label: 'Reflux / heartburn',
			Value: 'Reflux / heartburn',
			CodeName: 'Indication',
			ParentCodeValue: 'Gastroscopy',
			OrderingIndex: 13,
		},
		{
			Id: 43,
			Label: 'Weight loss',
			Value: 'Weight loss',
			CodeName: 'Indication',
			ParentCodeValue: 'Gastroscopy',
			OrderingIndex: 14,
		},
		{
			Id: 44,
			Label: 'Heartburn',
			Value: 'Heartburn',
			CodeName: 'Indication',
			ParentCodeValue: 'Gastroscopy',
			OrderingIndex: 15,
		},
		{
			Id: 45,
			Label: 'Raised tumor marker',
			Value: 'Raised tumor marker',
			CodeName: 'Indication',
			ParentCodeValue: 'Gastroscopy',
			OrderingIndex: 16,
		},
		{
			Id: 46,
			Label: 'Globus sensation',
			Value: 'Globus sensation',
			CodeName: 'Indication',
			ParentCodeValue: 'Gastroscopy',
			OrderingIndex: 17,
		},
	],
	Instrument: [
		{
			Id: 637,
			Label: 'CF-H260AL 2722451',
			Value: 'CF-H260AL 2722451',
			CodeName: 'Instrument',
			ParentCodeValue: 'Colonoscopy',
			OrderingIndex: 1,
		},
		{
			Id: 638,
			Label: 'CF-H260AL 2001289',
			Value: 'CF-H260AL 2001289',
			CodeName: 'Instrument',
			ParentCodeValue: 'Colonoscopy',
			OrderingIndex: 2,
		},
		{
			Id: 639,
			Label: 'CYF-240A 2000693',
			Value: 'CYF-240A 2000693',
			CodeName: 'Instrument',
			ParentCodeValue: 'Cystoscopy',
			OrderingIndex: 1,
		},
		{
			Id: 676,
			Label: 'CYF-2000693 (CYS)',
			Value: 'CYF-2000693 (CYS)',
			CodeName: 'Instrument',
			ParentCodeValue: 'Cystoscopy',
			OrderingIndex: 2,
		},
		{
			Id: 635,
			Label: 'GIF-H260 2345263',
			Value: 'GIF-H260 2345263',
			CodeName: 'Instrument',
			ParentCodeValue: 'Gastroscopy',
			OrderingIndex: 1,
		},
		{
			Id: 636,
			Label: 'GIF-H260 2243183',
			Value: 'GIF-H260 2243183',
			CodeName: 'Instrument',
			ParentCodeValue: 'Gastroscopy',
			OrderingIndex: 2,
		},
	],
	'MBI-AI': [
		{
			Id: 568,
			Label: 'NBI',
			Value: 'MBI',
			CodeName: 'MBI-AI',
			ParentCodeValue: '',
			OrderingIndex: 1,
		},
		{
			Id: 569,
			Label: 'AI',
			Value: 'AI',
			CodeName: 'MBI-AI',
			ParentCodeValue: '',
			OrderingIndex: 2,
		},
	],
	Procedure: [
		{
			Id: 441,
			Label: 'Colonoscopy (大腸內視鏡)',
			Value: 'Colonoscopy (大腸內視鏡)',
			CodeName: 'Procedure',
			ParentCodeValue: 'Colonoscopy',
			OrderingIndex: 1,
		},
		{
			Id: 442,
			Label: 'Polypectomy (瘜肉切除)',
			Value: 'Polypectomy (瘜肉切除)',
			CodeName: 'Procedure',
			ParentCodeValue: 'Colonoscopy',
			OrderingIndex: 2,
		},
		{
			Id: 443,
			Label: 'Banding of haemorrhoids (痔瘡結紮術)',
			Value: 'Banding of haemorrhoids (痔瘡結紮術)',
			CodeName: 'Procedure',
			ParentCodeValue: 'Colonoscopy',
			OrderingIndex: 3,
		},
		{
			Id: 444,
			Label: 'Biopsy (組織活檢)',
			Value: 'Biopsy (組織活檢)',
			CodeName: 'Procedure',
			ParentCodeValue: 'Colonoscopy',
			OrderingIndex: 4,
		},
		{
			Id: 445,
			Label: 'Haemostasis (止血程序)',
			Value: 'Haemostasis (止血程序)',
			CodeName: 'Procedure',
			ParentCodeValue: 'Colonoscopy',
			OrderingIndex: 5,
		},
		{
			Id: 446,
			Label: 'Sigmoidoscopy (乙狀結腸鏡檢查)',
			Value: 'Sigmoidoscopy (乙狀結腸鏡檢查)',
			CodeName: 'Procedure',
			ParentCodeValue: 'Colonoscopy',
			OrderingIndex: 6,
		},
		{
			Id: 447,
			Label: 'Foreign body removal (異物移除)',
			Value: 'Foreign body removal (異物移除)',
			CodeName: 'Procedure',
			ParentCodeValue: 'Colonoscopy',
			OrderingIndex: 7,
		},
		{
			Id: 434,
			Label: 'OGD (食道、胃、十二指腸內窺鏡)',
			Value: 'OGD (食道、胃、十二指腸內窺鏡)',
			CodeName: 'Procedure',
			ParentCodeValue: 'Gastroscopy',
			OrderingIndex: 1,
		},
		{
			Id: 435,
			Label: 'Biopsy + CLO Test (組織活檢+幽門螺旋菌測試)',
			Value: 'Biopsy + CLO Test (組織活檢+幽門螺旋菌測試)',
			CodeName: 'Procedure',
			ParentCodeValue: 'Gastroscopy',
			OrderingIndex: 2,
		},
		{
			Id: 436,
			Label: 'Polypectomy (瘜肉切除術)',
			Value: 'Polypectomy (瘜肉切除術)',
			CodeName: 'Procedure',
			ParentCodeValue: 'Gastroscopy',
			OrderingIndex: 3,
		},
		{
			Id: 437,
			Label: 'Biopsy (組織活檢)',
			Value: 'Biopsy (組織活檢)',
			CodeName: 'Procedure',
			ParentCodeValue: 'Gastroscopy',
			OrderingIndex: 4,
		},
		{
			Id: 438,
			Label: 'Haemostasis (止血程序)',
			Value: 'Haemostasis (止血程序)',
			CodeName: 'Procedure',
			ParentCodeValue: 'Gastroscopy',
			OrderingIndex: 5,
		},
		{
			Id: 439,
			Label: 'CLO Test (幽門螺旋菌測試)',
			Value: 'CLO Test (幽門螺旋菌測試)',
			CodeName: 'Procedure',
			ParentCodeValue: 'Gastroscopy',
			OrderingIndex: 6,
		},
		{
			Id: 440,
			Label: 'Foreign body removal (異物移除)',
			Value: 'Foreign body removal (異物移除)',
			CodeName: 'Procedure',
			ParentCodeValue: 'Gastroscopy',
			OrderingIndex: 7,
		},
	],
	ReportTemplate: Object.keys(fakeDefine).map((key, index) => {
		return {
			Id: 565,
			Label: key,
			Value: key,
			CodeName: 'ReportTemplate',
			ParentCodeValue: '',
			OrderingIndex: index,
		};
	}),
	ReportTitle: [
		{
			Id: 70,
			Label: 'Colonoscopy',
			Value: 'COLONOSCOPY REPORT',
			CodeName: 'ReportTitle',
			ParentCodeValue: '',
			OrderingIndex: 1,
		},
		{
			Id: 71,
			Label: 'Gastroscopy',
			Value: 'GASTROSCOPY REPORT',
			CodeName: 'ReportTitle',
			ParentCodeValue: '',
			OrderingIndex: 2,
		},
	],
	Sedation: [
		{
			Id: 54,
			Label: 'MAC',
			Value: 'MAC',
			CodeName: 'Sedation',
			ParentCodeValue: '',
			OrderingIndex: 1,
		},
		{
			Id: 58,
			Label: 'Midazolam',
			Value: 'Midazolam',
			CodeName: 'Sedation',
			ParentCodeValue: '',
			OrderingIndex: 2,
		},
		{
			Id: 60,
			Label: 'Fentanyl',
			Value: 'Fentanyl',
			CodeName: 'Sedation',
			ParentCodeValue: '',
			OrderingIndex: 3,
		},
		{
			Id: 633,
			Label: 'Dormicum',
			Value: 'Dormicum',
			CodeName: 'Sedation',
			ParentCodeValue: '',
			OrderingIndex: 4,
		},
		{
			Id: 640,
			Label: 'Buscopan',
			Value: 'Buscopan',
			CodeName: 'Sedation',
			ParentCodeValue: '',
			OrderingIndex: 4,
		},
		{
			Id: 634,
			Label: 'Propofol',
			Value: 'Propofol',
			CodeName: 'Sedation',
			ParentCodeValue: '',
			OrderingIndex: 5,
		},
		{
			Id: 730,
			Label: 'Pethidine',
			Value: 'Pethidine',
			CodeName: 'Sedation',
			ParentCodeValue: '',
			OrderingIndex: 6,
		},
	],
	YesNo: [
		{
			Id: 67,
			Label: 'Yes',
			Value: 'Yes',
			CodeName: 'YesNo',
			ParentCodeValue: '',
			OrderingIndex: 1,
		},
		{
			Id: 69,
			Label: 'No',
			Value: 'No',
			CodeName: 'YesNo',
			ParentCodeValue: '',
			OrderingIndex: 2,
		},
	],
	UserAccount: [
		{
			Id: 751161036,
			Label: 'Dr. Stephen Chan',
			Value: 'ckchan',
			CodeName: 'UserAccount',
			ParentCodeValue: '',
			OrderingIndex: 0,
		},
		{
			Id: -873715096,
			Label: 'Dr. Hung Ka Wai Ray',
			Value: 'kwhung',
			CodeName: 'UserAccount',
			ParentCodeValue: '',
			OrderingIndex: 0,
		},
		{
			Id: 775689603,
			Label: 'Dr. lisy',
			Value: 'lisy',
			CodeName: 'UserAccount',
			ParentCodeValue: '',
			OrderingIndex: 0,
		},
		{
			Id: 1433790059,
			Label: ' nurse',
			Value: 'nurse',
			CodeName: 'UserAccount',
			ParentCodeValue: '',
			OrderingIndex: 0,
		},
		{
			Id: -1939365154,
			Label: ' ',
			Value: 'teramed',
			CodeName: 'UserAccount',
			ParentCodeValue: '',
			OrderingIndex: 0,
		},
		{
			Id: 1448002985,
			Label: 'Mr. user',
			Value: 'user',
			CodeName: 'UserAccount',
			ParentCodeValue: '',
			OrderingIndex: 0,
		},
	],
};
