export const imageFieldsDefine: any[] = [
	{
		id: 'DescriptionOfFindings',
		type: 'CodeListLexiconInput',
		label: 'Findings',
		labelWidth: '35%',
		labelStyle: {
			backgroundColor: 'transparent',
			color: '#339966',
			fontSize: 10,
			fontFamily: 'Noto Sans TC',
			fontStyle: 'normal',
			fontWeight: '600',
			textAlign: 'left',
			textDecoration: 'none',
			marginTop: 0,
			marginRight: 0,
			marginBottom: 0,
			marginLeft: 0,
			paddingTop: 0,
			paddingRight: 0,
			paddingBottom: 0,
			paddingLeft: 0,
		},
		valueStyle: {
			backgroundColor: 'transparent',
			color: 'black',
			fontSize: 12,
			fontFamily: 'Noto Sans TC',
			fontStyle: 'normal',
			fontWeight: 'bold',
			textAlign: 'center',
			textDecoration: 'none',
			marginTop: 0,
			marginRight: 0,
			marginBottom: 0,
			marginLeft: 0,
			paddingTop: 0,
			paddingRight: 0,
			paddingBottom: 0,
			paddingLeft: 0,
		},
		defaultValue: '',
		initMapping: '',
		orientation: 'row',
		readOnly: false,
		buttonBar: [],
		validate: { type: 'none' },
		hint: '',
		hideLabel: false,
		fromModal: '',
		optionSource: { type: 'http', source: 'ImageFindings' },
		filterCondition: { filterById: 'ReportTemplate', filterOptionKey: 'ReportTemplate' },
		maxLength: 1000,
	},
	{
		id: 'DescriptionOfSites',
		type: 'CodeListLexiconInput',
		label: 'Site',
		labelWidth: '35%',
		labelStyle: {
			backgroundColor: 'transparent',
			color: '#339966',
			fontSize: 10,
			fontFamily: 'Noto Sans TC',
			fontStyle: 'normal',
			fontWeight: '600',
			textAlign: 'left',
			textDecoration: 'none',
			marginTop: 0,
			marginRight: 0,
			marginBottom: 0,
			marginLeft: 0,
			paddingTop: 0,
			paddingRight: 0,
			paddingBottom: 0,
			paddingLeft: 0,
		},
		valueStyle: {
			backgroundColor: 'transparent',
			color: 'black',
			fontSize: 12,
			fontFamily: 'Noto Sans TC',
			fontStyle: 'normal',
			fontWeight: 'bold',
			textAlign: 'center',
			textDecoration: 'none',
			marginTop: 0,
			marginRight: 0,
			marginBottom: 0,
			marginLeft: 0,
			paddingTop: 0,
			paddingRight: 0,
			paddingBottom: 0,
			paddingLeft: 0,
		},
		defaultValue: '',
		initMapping: '',
		orientation: 'row',
		readOnly: false,
		buttonBar: [],
		validate: { type: 'none' },
		hint: '',
		hideLabel: false,
		fromModal: '',
		optionSource: { type: 'http', source: 'ImageSites' },
		filterCondition: { filterById: 'ReportTemplate', filterOptionKey: 'ReportTemplate' },
		maxLength: 1000,
	},
];
