export const WoundDefine: any = {
	sections: [
		{
			id: 'sectionReportType',
			type: 'form',
			isHeader: false,
			subSections: [
				{
					id: 'subSection1',
					maxWidth: '100%',
					fields: [
						{
							id: 'Source',
							type: 'Text',
							hide: false,
							hideInPDF: false,
							label: '發生來源',
							labelWidth: '35%',
							labelStyle: {
								backgroundColor: 'transparent',
								color: '#0070c0',
								fontSize: 13,
								fontFamily: 'Microsoft JhengHei',
								fontStyle: 'normal',
								fontWeight: 'bold',
								textAlign: 'left',
								textDecoration: 'none',
								marginTop: 0,
								marginRight: 0,
								marginBottom: 0,
								marginLeft: 0,
								paddingTop: 0,
								paddingRight: 0,
								paddingBottom: 0,
								paddingLeft: 0,
								borderColor: 'black',
								borderStyle: 'solid',
								borderTop: 0,
								borderRight: 0,
								borderBottom: 0,
								borderLeft: 0,
							},
							valueStyle: {
								backgroundColor: 'transparent',
								color: 'black',
								fontSize: 12,
								fontFamily: 'Microsoft JhengHei',
								fontStyle: 'normal',
								fontWeight: 'bold',
								textAlign: 'right',
								textDecoration: 'none',
								marginTop: 0,
								marginRight: 0,
								marginBottom: 0,
								marginLeft: 0,
								paddingTop: 0,
								paddingRight: 0,
								paddingBottom: 0,
								paddingLeft: 0,
								borderColor: 'black',
								borderStyle: 'solid',
								borderTop: 0,
								borderRight: 0,
								borderBottom: 0,
								borderLeft: 0,
							},
							defaultValue: '',
							initMapping: '',
							orientation: 'row',
							readOnly: false,
							buttonBar: [],
							validate: { type: 'none' },
							hint: '',
							hideLabel: false,
							placeholder: '',
							suffix: '',
							prefix: '',
						},
						{
							id: 'Size',
							type: 'Text',
							hide: false,
							hideInPDF: false,
							label: '大小[長×寬]cm',
							labelWidth: '35%',
							labelStyle: {
								backgroundColor: 'transparent',
								color: '#0070c0',
								fontSize: 13,
								fontFamily: 'Microsoft JhengHei',
								fontStyle: 'normal',
								fontWeight: 'bold',
								textAlign: 'left',
								textDecoration: 'none',
								marginTop: 0,
								marginRight: 0,
								marginBottom: 0,
								marginLeft: 0,
								paddingTop: 0,
								paddingRight: 0,
								paddingBottom: 0,
								paddingLeft: 0,
								borderColor: 'black',
								borderStyle: 'solid',
								borderTop: 0,
								borderRight: 0,
								borderBottom: 0,
								borderLeft: 0,
							},
							valueStyle: {
								backgroundColor: 'transparent',
								color: 'black',
								fontSize: 12,
								fontFamily: 'Microsoft JhengHei',
								fontStyle: 'normal',
								fontWeight: 'bold',
								textAlign: 'left',
								textDecoration: 'none',
								marginTop: 0,
								marginRight: 0,
								marginBottom: 0,
								marginLeft: 0,
								paddingTop: 0,
								paddingRight: 0,
								paddingBottom: 0,
								paddingLeft: 0,
								borderColor: 'black',
								borderStyle: 'solid',
								borderTop: 0,
								borderRight: 0,
								borderBottom: 0,
								borderLeft: 0,
							},
							defaultValue: '',
							initMapping: '',
							orientation: 'row',
							readOnly: false,
							buttonBar: [],
							validate: { type: 'none' },
							hint: '',
							hideLabel: false,
							placeholder: '',
							suffix: '',
							prefix: '',
						},
						{
							id: 'Depth',
							type: 'CodeListSelection',
							hide: false,
							hideInPDF: false,
							label: '深度mm',
							labelWidth: '35%',
							labelStyle: {
								backgroundColor: 'transparent',
								color: '#0070c0',
								fontSize: 13,
								fontFamily: 'Microsoft JhengHei',
								fontStyle: 'normal',
								fontWeight: 'bold',
								textAlign: 'left',
								textDecoration: 'none',
								marginTop: 0,
								marginRight: 0,
								marginBottom: 0,
								marginLeft: 0,
								paddingTop: 0,
								paddingRight: 0,
								paddingBottom: 0,
								paddingLeft: 0,
								borderColor: 'black',
								borderStyle: 'solid',
								borderTop: 0,
								borderRight: 0,
								borderBottom: 0,
								borderLeft: 0,
							},
							valueStyle: {
								backgroundColor: 'transparent',
								color: 'black',
								fontSize: 12,
								fontFamily: 'Microsoft JhengHei',
								fontStyle: 'normal',
								fontWeight: 'bold',
								textAlign: 'left',
								textDecoration: 'none',
								marginTop: 0,
								marginRight: 0,
								marginBottom: 0,
								marginLeft: 0,
								paddingTop: 0,
								paddingRight: 0,
								paddingBottom: 0,
								paddingLeft: 0,
								borderColor: 'black',
								borderStyle: 'solid',
								borderTop: 0,
								borderRight: 0,
								borderBottom: 0,
								borderLeft: 0,
							},
							defaultValue: '',
							initMapping: '',
							orientation: 'row',
							readOnly: false,
							buttonBar: [],
							validate: { type: 'none' },
							hint: '',
							hideLabel: false,
							isMulti: false,
							optionSource: { type: 'http', source: 'ReportTemplate', labelKey: 'label', key: 'label' },
							filterCondition: { filterById: '', filterOptionKey: '' },
							joinStr: ',',
						},
						{
							id: 'PressureUlcerStage',
							type: 'Text',
							hide: false,
							hideInPDF: false,
							label: '壓傷等級',
							labelWidth: '35%',
							labelStyle: {
								backgroundColor: 'transparent',
								color: '#0070c0',
								fontSize: 13,
								fontFamily: 'Microsoft JhengHei',
								fontStyle: 'normal',
								fontWeight: 'bold',
								textAlign: 'left',
								textDecoration: 'none',
								marginTop: 0,
								marginRight: 0,
								marginBottom: 0,
								marginLeft: 0,
								paddingTop: 0,
								paddingRight: 0,
								paddingBottom: 0,
								paddingLeft: 0,
								borderColor: 'black',
								borderStyle: 'solid',
								borderTop: 0,
								borderRight: 0,
								borderBottom: 0,
								borderLeft: 0,
							},
							valueStyle: {
								backgroundColor: 'transparent',
								color: 'black',
								fontSize: 12,
								fontFamily: 'Microsoft JhengHei',
								fontStyle: 'normal',
								fontWeight: 'bold',
								textAlign: 'left',
								textDecoration: 'none',
								marginTop: 0,
								marginRight: 0,
								marginBottom: 0,
								marginLeft: 0,
								paddingTop: 0,
								paddingRight: 0,
								paddingBottom: 0,
								paddingLeft: 0,
								borderColor: 'black',
								borderStyle: 'solid',
								borderTop: 0,
								borderRight: 0,
								borderBottom: 0,
								borderLeft: 0,
							},
							defaultValue: '',
							initMapping: '',
							orientation: 'row',
							readOnly: false,
							buttonBar: [],
							validate: { type: 'none' },
							hint: '',
							hideLabel: false,
							placeholder: '',
							suffix: '',
							prefix: '',
						},
						{
							id: 'ExudateSmell',
							type: 'Text',
							hide: false,
							hideInPDF: false,
							label: '分泌物異味',
							labelWidth: '35%',
							labelStyle: {
								backgroundColor: 'transparent',
								color: '#0070c0',
								fontSize: 13,
								fontFamily: 'Microsoft JhengHei',
								fontStyle: 'normal',
								fontWeight: 'bold',
								textAlign: 'left',
								textDecoration: 'none',
								marginTop: 0,
								marginRight: 0,
								marginBottom: 0,
								marginLeft: 0,
								paddingTop: 0,
								paddingRight: 0,
								paddingBottom: 0,
								paddingLeft: 0,
								borderColor: 'black',
								borderStyle: 'solid',
								borderTop: 0,
								borderRight: 0,
								borderBottom: 0,
								borderLeft: 0,
							},
							valueStyle: {
								backgroundColor: 'transparent',
								color: 'black',
								fontSize: 12,
								fontFamily: 'Microsoft JhengHei',
								fontStyle: 'normal',
								fontWeight: 'bold',
								textAlign: 'left',
								textDecoration: 'none',
								marginTop: 0,
								marginRight: 0,
								marginBottom: 0,
								marginLeft: 0,
								paddingTop: 0,
								paddingRight: 0,
								paddingBottom: 0,
								paddingLeft: 0,
								borderColor: 'black',
								borderStyle: 'solid',
								borderTop: 0,
								borderRight: 0,
								borderBottom: 0,
								borderLeft: 0,
							},
							defaultValue: '',
							initMapping: '',
							orientation: 'row',
							readOnly: false,
							buttonBar: [],
							validate: { type: 'none' },
							hint: '',
							hideLabel: false,
							placeholder: '',
							suffix: '',
							prefix: '',
						},
						{
							id: 'ExudateVolume',
							type: 'Text',
							hide: false,
							hideInPDF: false,
							label: '分泌物量',
							labelWidth: '35%',
							labelStyle: {
								backgroundColor: 'transparent',
								color: '#0070c0',
								fontSize: 13,
								fontFamily: 'Microsoft JhengHei',
								fontStyle: 'normal',
								fontWeight: 'bold',
								textAlign: 'left',
								textDecoration: 'none',
								marginTop: 0,
								marginRight: 0,
								marginBottom: 0,
								marginLeft: 0,
								paddingTop: 0,
								paddingRight: 0,
								paddingBottom: 0,
								paddingLeft: 0,
								borderColor: 'black',
								borderStyle: 'solid',
								borderTop: 0,
								borderRight: 0,
								borderBottom: 0,
								borderLeft: 0,
							},
							valueStyle: {
								backgroundColor: 'transparent',
								color: 'black',
								fontSize: 12,
								fontFamily: 'Microsoft JhengHei',
								fontStyle: 'normal',
								fontWeight: 'bold',
								textAlign: 'left',
								textDecoration: 'none',
								marginTop: 0,
								marginRight: 0,
								marginBottom: 0,
								marginLeft: 0,
								paddingTop: 0,
								paddingRight: 0,
								paddingBottom: 0,
								paddingLeft: 0,
								borderColor: 'black',
								borderStyle: 'solid',
								borderTop: 0,
								borderRight: 0,
								borderBottom: 0,
								borderLeft: 0,
							},
							defaultValue: '',
							initMapping: '',
							orientation: 'row',
							readOnly: false,
							buttonBar: [],
							validate: { type: 'none' },
							hint: '',
							hideLabel: false,
							placeholder: '',
							suffix: '',
							prefix: '',
						},
						{
							id: 'WoundColor',
							type: 'Text',
							hide: false,
							hideInPDF: false,
							label: '傷口顏色',
							labelWidth: '35%',
							labelStyle: {
								backgroundColor: 'transparent',
								color: '#0070c0',
								fontSize: 13,
								fontFamily: 'Microsoft JhengHei',
								fontStyle: 'normal',
								fontWeight: 'bold',
								textAlign: 'left',
								textDecoration: 'none',
								marginTop: 0,
								marginRight: 0,
								marginBottom: 0,
								marginLeft: 0,
								paddingTop: 0,
								paddingRight: 0,
								paddingBottom: 0,
								paddingLeft: 0,
								borderColor: 'black',
								borderStyle: 'solid',
								borderTop: 0,
								borderRight: 0,
								borderBottom: 0,
								borderLeft: 0,
							},
							valueStyle: {
								backgroundColor: 'transparent',
								color: 'black',
								fontSize: 12,
								fontFamily: 'Microsoft JhengHei',
								fontStyle: 'normal',
								fontWeight: 'bold',
								textAlign: 'left',
								textDecoration: 'none',
								marginTop: 0,
								marginRight: 0,
								marginBottom: 0,
								marginLeft: 0,
								paddingTop: 0,
								paddingRight: 0,
								paddingBottom: 0,
								paddingLeft: 0,
								borderColor: 'black',
								borderStyle: 'solid',
								borderTop: 0,
								borderRight: 0,
								borderBottom: 0,
								borderLeft: 0,
							},
							defaultValue: '',
							initMapping: '',
							orientation: 'row',
							readOnly: false,
							buttonBar: [],
							validate: { type: 'none' },
							hint: '',
							hideLabel: false,
							placeholder: '',
							suffix: '',
							prefix: '',
						},
						{
							id: 'DressingMethod',
							type: 'Text',
							hide: false,
							hideInPDF: false,
							label: '換藥方式',
							labelWidth: '35%',
							labelStyle: {
								backgroundColor: 'transparent',
								color: '#0070c0',
								fontSize: 13,
								fontFamily: 'Microsoft JhengHei',
								fontStyle: 'normal',
								fontWeight: 'bold',
								textAlign: 'left',
								textDecoration: 'none',
								marginTop: 0,
								marginRight: 0,
								marginBottom: 0,
								marginLeft: 0,
								paddingTop: 0,
								paddingRight: 0,
								paddingBottom: 0,
								paddingLeft: 0,
								borderColor: 'black',
								borderStyle: 'solid',
								borderTop: 0,
								borderRight: 0,
								borderBottom: 0,
								borderLeft: 0,
							},
							valueStyle: {
								backgroundColor: 'transparent',
								color: 'black',
								fontSize: 12,
								fontFamily: 'Microsoft JhengHei',
								fontStyle: 'normal',
								fontWeight: 'bold',
								textAlign: 'left',
								textDecoration: 'none',
								marginTop: 0,
								marginRight: 0,
								marginBottom: 0,
								marginLeft: 0,
								paddingTop: 0,
								paddingRight: 0,
								paddingBottom: 0,
								paddingLeft: 0,
								borderColor: 'black',
								borderStyle: 'solid',
								borderTop: 0,
								borderRight: 0,
								borderBottom: 0,
								borderLeft: 0,
							},
							defaultValue: '',
							initMapping: '',
							orientation: 'row',
							readOnly: false,
							buttonBar: [],
							validate: { type: 'none' },
							hint: '',
							hideLabel: false,
							placeholder: '',
							suffix: '',
							prefix: '',
						},
						{
							id: 'Treatment',
							type: 'Text',
							hide: false,
							hideInPDF: false,
							label: '處置',
							labelWidth: '35%',
							labelStyle: {
								backgroundColor: 'transparent',
								color: '#0070c0',
								fontSize: 13,
								fontFamily: 'Microsoft JhengHei',
								fontStyle: 'normal',
								fontWeight: 'bold',
								textAlign: 'left',
								textDecoration: 'none',
								marginTop: 0,
								marginRight: 0,
								marginBottom: 0,
								marginLeft: 0,
								paddingTop: 0,
								paddingRight: 0,
								paddingBottom: 0,
								paddingLeft: 0,
								borderColor: 'black',
								borderStyle: 'solid',
								borderTop: 0,
								borderRight: 0,
								borderBottom: 0,
								borderLeft: 0,
							},
							valueStyle: {
								backgroundColor: 'transparent',
								color: 'black',
								fontSize: 12,
								fontFamily: 'Microsoft JhengHei',
								fontStyle: 'normal',
								fontWeight: 'bold',
								textAlign: 'left',
								textDecoration: 'none',
								marginTop: 0,
								marginRight: 0,
								marginBottom: 0,
								marginLeft: 0,
								paddingTop: 0,
								paddingRight: 0,
								paddingBottom: 0,
								paddingLeft: 0,
								borderColor: 'black',
								borderStyle: 'solid',
								borderTop: 0,
								borderRight: 0,
								borderBottom: 0,
								borderLeft: 0,
							},
							defaultValue: '',
							initMapping: '',
							orientation: 'row',
							readOnly: false,
							buttonBar: [],
							validate: { type: 'none' },
							hint: '',
							hideLabel: false,
							placeholder: '',
							suffix: '',
							prefix: '',
						},
						{
							id: 'Remark',
							type: 'Text',
							hide: false,
							hideInPDF: false,
							label: '備註',
							labelWidth: '35%',
							labelStyle: {
								backgroundColor: 'transparent',
								color: '#0070c0',
								fontSize: 13,
								fontFamily: 'Microsoft JhengHei',
								fontStyle: 'normal',
								fontWeight: 'bold',
								textAlign: 'left',
								textDecoration: 'none',
								marginTop: 0,
								marginRight: 0,
								marginBottom: 0,
								marginLeft: 0,
								paddingTop: 0,
								paddingRight: 0,
								paddingBottom: 0,
								paddingLeft: 0,
								borderColor: 'black',
								borderStyle: 'solid',
								borderTop: 0,
								borderRight: 0,
								borderBottom: 0,
								borderLeft: 0,
							},
							valueStyle: {
								backgroundColor: 'transparent',
								color: 'black',
								fontSize: 12,
								fontFamily: 'Microsoft JhengHei',
								fontStyle: 'normal',
								fontWeight: 'bold',
								textAlign: 'left',
								textDecoration: 'none',
								marginTop: 0,
								marginRight: 0,
								marginBottom: 0,
								marginLeft: 0,
								paddingTop: 0,
								paddingRight: 0,
								paddingBottom: 0,
								paddingLeft: 0,
								borderColor: 'black',
								borderStyle: 'solid',
								borderTop: 0,
								borderRight: 0,
								borderBottom: 0,
								borderLeft: 0,
							},
							defaultValue: '',
							initMapping: '',
							orientation: 'row',
							readOnly: false,
							buttonBar: [],
							validate: { type: 'none' },
							hint: '',
							hideLabel: false,
							placeholder: '',
							suffix: '',
							prefix: '',
						},
						{
							id: 'Evaluator',
							type: 'Text',
							hide: false,
							hideInPDF: false,
							label: '評估人員',
							labelWidth: '35%',
							labelStyle: {
								backgroundColor: 'transparent',
								color: '#0070c0',
								fontSize: 13,
								fontFamily: 'Microsoft JhengHei',
								fontStyle: 'normal',
								fontWeight: 'bold',
								textAlign: 'left',
								textDecoration: 'none',
								marginTop: 0,
								marginRight: 0,
								marginBottom: 0,
								marginLeft: 0,
								paddingTop: 0,
								paddingRight: 0,
								paddingBottom: 0,
								paddingLeft: 0,
								borderColor: 'black',
								borderStyle: 'solid',
								borderTop: 0,
								borderRight: 0,
								borderBottom: 0,
								borderLeft: 0,
							},
							valueStyle: {
								backgroundColor: 'transparent',
								color: 'black',
								fontSize: 12,
								fontFamily: 'Microsoft JhengHei',
								fontStyle: 'normal',
								fontWeight: 'bold',
								textAlign: 'left',
								textDecoration: 'none',
								marginTop: 0,
								marginRight: 0,
								marginBottom: 0,
								marginLeft: 0,
								paddingTop: 0,
								paddingRight: 0,
								paddingBottom: 0,
								paddingLeft: 0,
								borderColor: 'black',
								borderStyle: 'solid',
								borderTop: 0,
								borderRight: 0,
								borderBottom: 0,
								borderLeft: 0,
							},
							defaultValue: '',
							initMapping: '',
							orientation: 'row',
							readOnly: false,
							buttonBar: [],
							validate: { type: 'none' },
							hint: '',
							hideLabel: false,
							placeholder: '',
							suffix: '',
							prefix: '',
						},
					],
					style: { color: 'transparent' },
				},
			],
			maxWidth: '100%',
			hideInPDF: false,
			style: {
				backgroundColor: 'transparent',
				paddingRight: 0,
				paddingLeft: 0,
				marginTop: 0,
				marginBottom: 0,
				marginLeft: 0,
				marginRight: 0,
				paddingTop: 0,
				paddingBottom: 0,
				borderTop: 0,
				borderBottom: 0,
				borderLeft: 0,
				borderRight: 0,
			},
		},
	],
};
