import './App.css';
import { RecoilRoot } from 'recoil';

import { ISVReport } from '../lib/components/ISVReport';
import { FormDefine } from '../lib/types/define.ts';

const initialFormData = {
	StudyInstanceUID: '1.3.6.1.4.1.54514.20240314115126.1.9494.278',
	StudyDate: '20240411',
	PatientId: 'test',
	PatientsName: 'test',
	PatientsSex: 'M',
	PatientsBirthDate: '20240303',
	PatientAge: '0',
	Version: '1',
	ReportStatus: 'Saved',
	Author: 'user',
	ReportAttachmentData: [
		{
			Id: 253,
			AttachmentType: 'ReferringLetter',
			FilePath:
				'http://192.168.50.214:8080//attachment\\1.3.6.1.4.1.54514.20240314115126.1.9494.278_ReferringLetter_1.pdf',
		},
		{
			Id: 254,
			AttachmentType: 'OldReport',
			FilePath:
				'http://192.168.50.214:8080//attachment\\1.3.6.1.4.1.54514.20240314115126.1.9494.278_OldReport_1.jpg',
		},
	],
	AccessionNumber: 'S220240314001',
	StudyDescription: 'ddddddd',
	Modality: 'US',
	DateTime: '2024-07-16T14:26:34',
	ReferringPhysiciansName: '',
	NameofPhysiciansReading: 'DR01004',
	PerformingPhysiciansName: 'DR01004',
	ReportTemplate: 'Grid',
	LastSignOffExecuteTime: '',
	UserId: 'user',
	DoctorinCharge: 'user',
	Endoscopist1: 'user',
	Indication: '',
	DiagramData:
		'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+ip1sAAAAASUVORK5CYII=',
	DiagramMarkers: [],
	Other: '',
	OtherDescription: '',
	OccurrenceofComplication: '',
	PlannedforPartialColonoscopy: '',
	BowelPreparation: '',
	PostRighthemicolectomy: '',
	TechnicalDifficulties: '',
	MechanicalObstruction: '',
	IsCaecumReached: '',
	WithdrawalTime: 0,
	QualityOfBowelPreparation: '',
	QualityBowelScore: 0,
	BBPS_Left: -1,
	BBPS_Right: -1,
	BBPS_Transverse: -1,
	Sedation: [{ SedationDrug: '', SedationDosage: '', SedationDosageUnit: '' }],
	BowelPrepQuality: 'Excellent',
	ReportDate: '2024-07-16',
	TableBreastLesion: [
		{
			location: 'R_H',
			nature: '瑞克·格萊姆斯的妻子。是這一小隊倖存者的情感中樞，並且努力維持着他們的道德和行為。她是一位具有自我保護意識母親，不顧一切的保護她的兒子卡爾的安全，也因此對他人非常多疑，不易接近。與瑞克重逢後，她果斷地與肖恩·威爾士斷絕了關係。後來她懷孕了，但卻不知道孩子是瑞克的還是肖恩的。經過一番掙扎，她決定把孩子生下來，並向瑞克坦白了一切。',
			'cm-fm': '20',
			size: '40',
			'bi-RADS': 'Test',
		},
	],
};

const formDefine = {
	sections: [
		{
			id: 'sectionReportType',
			type: 'form',
			subSections: [
				{
					id: 'subSection_2',
					maxWidth: '50%',
					fields: [
						{
							id: 'ReportTemplate',
							label: 'Report Template',
							type: 'CodeListSelection',
							orientation: 'row',
							optionSource: {
								type: 'http',
								source: 'ReportTemplate',
								labelKey: 'label',
								key: 'value',
							},
							validate: {
								type: 'required',
							},
							labelStyle: {
								color: '#0070c0',
								fontFamily: 'Noto Sans TC',
								fontWeight: 'bold',
								fontSize: '10',
								backgroundColor: 'transparent',
							},
							valueStyle: {
								fontSize: '10',
								fontFamily: 'Noto Sans TC',
								fontWeight: 'bold',
								color: 'black',
							},
						},
					],
				},
				{
					id: 'subSection_1',
					maxWidth: '50%',
					fields: [],
				},
			],
			maxWidth: '100%',
			hideInPDF: true,
			style: {
				backgroundColor: '#dadada',
			},
		},
		{
			id: 'sectionPatientInfo',
			type: 'form',
			subSections: [
				{
					id: 'subSection_1',
					maxWidth: '50%',
					fields: [
						{
							id: 'PatientsName',
							label: 'Patient Name',
							orientation: 'row',
							type: 'Text',
							readOnly: true,
							labelStyle: {
								color: '#0070c0',
								fontFamily: 'Noto Sans TC',
								fontWeight: 'bold',
								fontSize: '10',
							},
							valueStyle: {
								fontSize: '10',
								fontFamily: 'Noto Sans TC',
								fontWeight: 'bold',
								color: 'black',
							},
						},
						{
							id: 'AccessionNumber',
							type: 'Text',
							label: 'Patient No.',
							labelWidth: '35%',
							labelStyle: {
								backgroundColor: 'transparent',
								color: '#0070c0',
								fontSize: '10',
								fontFamily: 'Noto Sans TC',
								fontStyle: 'normal',
								fontWeight: 'bold',
								textAlign: 'left',
								textDecoration: 'none',
								marginTop: 0,
								marginRight: 0,
								marginBottom: 0,
								marginLeft: 0,
								paddingTop: 0,
								paddingRight: 0,
								paddingBottom: 0,
								paddingLeft: 0,
							},
							valueStyle: {
								backgroundColor: 'transparent',
								color: 'black',
								fontSize: '10',
								fontFamily: 'Noto Sans TC',
								fontStyle: 'normal',
								fontWeight: 'bold',
								textAlign: 'left',
								textDecoration: 'none',
								marginTop: 0,
								marginRight: 0,
								marginBottom: 0,
								marginLeft: 0,
								paddingTop: 0,
								paddingRight: 0,
								paddingBottom: 0,
								paddingLeft: 0,
							},
							defaultValue: '',
							initMapping: '',
							orientation: 'row',
							readOnly: true,
							buttonBar: [],
							validate: {
								type: 'none',
							},
							hint: '',
							hideLabel: false,
							fromModal: '',
							placeholder: '',
							suffix: '',
							prefix: '',
						},
						{
							id: 'PatientId',
							type: 'Text',
							label: 'ID No.',
							labelWidth: '35%',
							labelStyle: {
								backgroundColor: 'transparent',
								color: '#0070c0',
								fontSize: '10',
								fontFamily: 'Noto Sans TC',
								fontStyle: 'normal',
								fontWeight: 'bold',
								textAlign: 'left',
								textDecoration: 'none',
								marginTop: 0,
								marginRight: 0,
								marginBottom: 0,
								marginLeft: 0,
								paddingTop: 0,
								paddingRight: 0,
								paddingBottom: 0,
								paddingLeft: 0,
							},
							valueStyle: {
								backgroundColor: 'transparent',
								color: 'black',
								fontSize: '10',
								fontFamily: 'Noto Sans TC',
								fontStyle: 'normal',
								fontWeight: 'bold',
								textAlign: 'left',
								textDecoration: 'none',
								marginTop: 0,
								marginRight: 0,
								marginBottom: 0,
								marginLeft: 0,
								paddingTop: 0,
								paddingRight: 0,
								paddingBottom: 0,
								paddingLeft: 0,
							},
							defaultValue: '',
							initMapping: '',
							orientation: 'row',
							readOnly: true,
							buttonBar: [],
							validate: {
								type: 'none',
							},
							hint: '',
							hideLabel: false,
							fromModal: '',
							placeholder: '',
							suffix: '',
							prefix: '',
						},
						{
							id: 'PatientsSex',
							type: 'Text',
							label: 'Gender',
							labelWidth: '35%',
							labelStyle: {
								backgroundColor: 'transparent',
								color: '#0070c0',
								fontSize: '10',
								fontFamily: 'Noto Sans TC',
								fontStyle: 'normal',
								fontWeight: 'bold',
								textAlign: 'left',
								textDecoration: 'none',
								marginTop: 0,
								marginRight: 0,
								marginBottom: 0,
								marginLeft: 0,
								paddingTop: 0,
								paddingRight: 0,
								paddingBottom: 0,
								paddingLeft: 0,
							},
							valueStyle: {
								backgroundColor: 'transparent',
								color: 'black',
								fontSize: '10',
								fontFamily: 'Noto Sans TC',
								fontStyle: 'normal',
								fontWeight: 'bold',
								textAlign: 'left',
								textDecoration: 'none',
								marginTop: 0,
								marginRight: 0,
								marginBottom: 0,
								marginLeft: 0,
								paddingTop: 0,
								paddingRight: 0,
								paddingBottom: 0,
								paddingLeft: 0,
							},
							defaultValue: '',
							initMapping: '',
							orientation: 'row',
							readOnly: true,
							buttonBar: [],
							validate: {
								type: 'none',
							},
							hint: '',
							hideLabel: false,
							fromModal: '',
							placeholder: '',
							suffix: '',
							prefix: '',
						},
						{
							id: 'PatientsBirthDate',
							type: 'DatePicker',
							label: 'Date of Birth',
							labelWidth: '35%',
							labelStyle: {
								backgroundColor: 'transparent',
								color: '#0070c0',
								fontSize: '10',
								fontFamily: 'Noto Sans TC',
								fontStyle: 'normal',
								fontWeight: 'bold',
								textAlign: 'left',
								textDecoration: 'none',
								marginTop: 0,
								marginRight: 0,
								marginBottom: 0,
								marginLeft: 0,
								paddingTop: 0,
								paddingRight: 0,
								paddingBottom: 0,
								paddingLeft: 0,
							},
							valueStyle: {
								backgroundColor: 'transparent',
								color: 'black',
								fontSize: '10',
								fontFamily: 'Noto Sans TC',
								fontStyle: 'normal',
								fontWeight: 'bold',
								textAlign: 'left',
								textDecoration: 'none',
								marginTop: 0,
								marginRight: 0,
								marginBottom: 0,
								marginLeft: 0,
								paddingTop: 0,
								paddingRight: 0,
								paddingBottom: 0,
								paddingLeft: 0,
							},
							defaultValue: '',
							initMapping: 'PatientsBirthDate',
							orientation: 'row',
							readOnly: true,
							buttonBar: [],
							validate: {
								type: 'none',
							},
							hint: '',
							hideLabel: false,
							fromModal: '',
							defaultToday: false,
							fromFormat: 'yyyyMMdd',
							toFormat: 'dd/MM/yyyy',
						},
						{
							id: 'PatientsAge',
							type: 'Text',
							label: 'Age',
							labelWidth: '35%',
							labelStyle: {
								backgroundColor: 'transparent',
								color: '#0070c0',
								fontSize: '10',
								fontFamily: 'Noto Sans TC',
								fontStyle: 'normal',
								fontWeight: 'bold',
								textAlign: 'left',
								textDecoration: 'none',
								marginTop: 0,
								marginRight: 0,
								marginBottom: 0,
								marginLeft: 0,
								paddingTop: 0,
								paddingRight: 0,
								paddingBottom: 0,
								paddingLeft: 0,
							},
							valueStyle: {
								backgroundColor: 'transparent',
								color: 'black',
								fontSize: '10',
								fontFamily: 'Noto Sans TC',
								fontStyle: 'normal',
								fontWeight: 'bold',
								textAlign: 'left',
								textDecoration: 'none',
								marginTop: 0,
								marginRight: 0,
								marginBottom: 0,
								marginLeft: 0,
								paddingTop: 0,
								paddingRight: 0,
								paddingBottom: 0,
								paddingLeft: 0,
							},
							defaultValue: '',
							initMapping: '',
							orientation: 'row',
							readOnly: true,
							buttonBar: [],
							validate: {
								type: 'none',
							},
							hint: '',
							hideLabel: false,
							fromModal: '',
							placeholder: '',
							suffix: '',
							prefix: '',
						},
					],
				},
				{
					id: 'subSection_2',
					maxWidth: '50%',
					fields: [
						{
							id: 'StudyDate',
							type: 'DatePicker',
							label: 'Date of Procedure',
							labelWidth: '35%',
							labelStyle: {
								color: '#0070c0',
								fontFamily: 'Noto Sans TC',
								fontWeight: 'bold',
								fontSize: '10',
							},
							valueStyle: {
								fontSize: '10',
								fontFamily: 'Noto Sans TC',
								fontWeight: 'bold',
								color: 'black',
							},
							defaultValue: '',
							initMapping: 'StudyDate',
							orientation: 'row',
							readOnly: false,
							buttonBar: [],
							validate: {
								type: 'none',
							},
							hint: '',
							hideLabel: false,
							fromModal: '',
							defaultToday: false,
							fromFormat: 'yyyyMMdd',
							toFormat: 'dd/MM/yyyy',
						},
						{
							id: 'DoctorinCharge',
							type: 'CodeListSelection',
							label: 'Doctor in Charge',
							labelWidth: '35%',
							labelStyle: {
								backgroundColor: 'transparent',
								color: '#0070c0',
								fontSize: '10',
								fontFamily: 'Noto Sans TC',
								fontStyle: 'normal',
								fontWeight: 'bold',
								textAlign: 'left',
								textDecoration: 'none',
								marginTop: 0,
								marginRight: 0,
								marginBottom: 0,
								marginLeft: 0,
								paddingTop: 0,
								paddingRight: 0,
								paddingBottom: 0,
								paddingLeft: 0,
							},
							valueStyle: {
								backgroundColor: 'transparent',
								color: 'black',
								fontSize: '10',
								fontFamily: 'Noto Sans TC',
								fontStyle: 'normal',
								fontWeight: 'bold',
								textAlign: 'left',
								textDecoration: 'none',
								marginTop: 0,
								marginRight: 0,
								marginBottom: 0,
								marginLeft: 0,
								paddingTop: 0,
								paddingRight: 0,
								paddingBottom: 0,
								paddingLeft: 0,
							},
							defaultValue: '',
							initMapping: 'UserId',
							orientation: 'row',
							readOnly: false,
							buttonBar: [],
							validate: {
								type: 'none',
							},
							hint: '',
							hideLabel: false,
							fromModal: '',
							isMulti: false,
							optionSource: {
								type: 'http',
								source: 'UserAccount',
							},
							filterCondition: {
								filterById: '',
								filterOptionKey: '',
							},
							joinStr: ',',
							fetchLatest: true,
						},
						{
							id: 'Endoscopist1',
							type: 'CodeListSelection',
							label: 'Endoscopist',
							labelWidth: '35%',
							labelStyle: {
								backgroundColor: 'transparent',
								color: '#0070c0',
								fontSize: '10',
								fontFamily: 'Noto Sans TC',
								fontStyle: 'normal',
								fontWeight: 'bold',
								textAlign: 'left',
								textDecoration: 'none',
								marginTop: 0,
								marginRight: 0,
								marginBottom: 0,
								marginLeft: 0,
								paddingTop: 0,
								paddingRight: 0,
								paddingBottom: 0,
								paddingLeft: 0,
							},
							valueStyle: {
								backgroundColor: 'transparent',
								color: 'black',
								fontSize: '10',
								fontFamily: 'Noto Sans TC',
								fontStyle: 'normal',
								fontWeight: 'bold',
								textAlign: 'left',
								textDecoration: 'none',
								marginTop: 0,
								marginRight: 0,
								marginBottom: 0,
								marginLeft: 0,
								paddingTop: 0,
								paddingRight: 0,
								paddingBottom: 0,
								paddingLeft: 0,
							},
							defaultValue: '',
							initMapping: 'UserId',
							orientation: 'row',
							readOnly: false,
							buttonBar: [],
							validate: {
								type: 'none',
							},
							hint: '',
							hideLabel: false,
							fromModal: '',
							isMulti: false,
							optionSource: {
								type: 'http',
								source: 'UserAccount',
							},
							filterCondition: {
								filterById: '',
								filterOptionKey: '',
							},
							joinStr: ',',
							fetchLatest: true,
						},
						{
							id: 'Anesthesiologist',
							type: 'CodeListSelection',
							label: 'Mac by Anesthetist',
							labelWidth: '35%',
							labelStyle: {
								backgroundColor: 'transparent',
								color: '#0070c0',
								fontSize: '10',
								fontFamily: 'Noto Sans TC',
								fontStyle: 'normal',
								fontWeight: 'bold',
								textAlign: 'left',
								textDecoration: 'none',
								marginTop: 0,
								marginRight: 0,
								marginBottom: 0,
								marginLeft: 0,
								paddingTop: 0,
								paddingRight: 0,
								paddingBottom: 0,
								paddingLeft: 0,
							},
							valueStyle: {
								backgroundColor: 'transparent',
								color: 'black',
								fontSize: '10',
								fontFamily: 'Noto Sans TC',
								fontStyle: 'normal',
								fontWeight: 'bold',
								textAlign: 'left',
								textDecoration: 'none',
								marginTop: 0,
								marginRight: 0,
								marginBottom: 0,
								marginLeft: 0,
								paddingTop: 0,
								paddingRight: 0,
								paddingBottom: 0,
								paddingLeft: 0,
							},
							defaultValue: '',
							initMapping: '',
							orientation: 'row',
							readOnly: false,
							buttonBar: [],
							validate: {
								type: 'none',
							},
							hint: '',
							hideLabel: false,
							fromModal: '',
							isMulti: true,
							optionSource: {
								type: 'http',
								source: 'Anaesthetist',
							},
							filterCondition: {
								filterById: '',
								filterOptionKey: '',
							},
							joinStr: ',',
							fetchLatest: false,
						},
						{
							id: 'ReferringPhysiciansName',
							type: 'Text',
							label: 'Referring Doctor',
							labelWidth: '35%',
							labelStyle: {
								backgroundColor: 'transparent',
								color: '#0070c0',
								fontSize: '10',
								fontFamily: 'Noto Sans TC',
								fontStyle: 'normal',
								fontWeight: 'bold',
								textAlign: 'left',
								textDecoration: 'none',
								marginTop: 0,
								marginRight: 0,
								marginBottom: 0,
								marginLeft: 0,
								paddingTop: 0,
								paddingRight: 0,
								paddingBottom: 0,
								paddingLeft: 0,
							},
							valueStyle: {
								backgroundColor: 'transparent',
								color: 'black',
								fontSize: '10',
								fontFamily: 'Noto Sans TC',
								fontStyle: 'normal',
								fontWeight: 'bold',
								textAlign: 'left',
								textDecoration: 'none',
								marginTop: 0,
								marginRight: 0,
								marginBottom: 0,
								marginLeft: 0,
								paddingTop: 0,
								paddingRight: 0,
								paddingBottom: 0,
								paddingLeft: 0,
							},
							defaultValue: '',
							initMapping: '',
							orientation: 'row',
							readOnly: true,
							buttonBar: [],
							validate: {
								type: 'none',
							},
							hint: '',
							hideLabel: false,
							fromModal: '',
							placeholder: '',
							suffix: '',
							prefix: '',
						},
					],
				},
			],
			maxWidth: '100%',
			style: {
				backgroundColor: '#dadada',
				paddingTop: 0,
				paddingRight: 0,
				paddingBottom: 0,
				paddingLeft: 0,
			},
		},
	],
} as FormDefine;

function App() {
	return (
		<RecoilRoot>
			<ISVReport
				codeList={{
					ReportTemplate: [
						{
							label: 'label111111111111111111111111111111111111112222222222222222',
							value: 'value1',
						},
					],
				}}
				formData={initialFormData}
				formDefine={formDefine}
			/>
		</RecoilRoot>
	);
}

export default App;
